=== phollemans/cwutils/resources/noaa/coastwatch/io/binaryStream.xsd
<?xml version="1.0"?>

<!-- 

     FILE: binaryStream.xsd
  PURPOSE: Defines the binary stream schema for reading arbitrary
           streams of binary data.
   AUTHOR: Peter Hollemans
     DATE: 2007/08/30
  CHANGES: n/a

  CoastWatch Software Library and Utilities
  Copyright 2007, USDOC/NOAA/NESDIS CoastWatch

-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://coastwatch.noaa.gov"
  xmlns="http://coastwatch.noaa.gov"
  elementFormDefault="qualified">

<xs:complexType name="entryType">
  <xs:attribute name="key" type="xs:string" use="required"/>
  <xs:attribute name="value" type="xs:string" use="required"/>
</xs:complexType>

<xs:simpleType name="mapValueType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="byte"/>
    <xs:enumeration value="ubyte"/>
    <xs:enumeration value="short"/>
    <xs:enumeration value="ushort"/>
    <xs:enumeration value="int"/>
    <xs:enumeration value="uint"/>
    <xs:enumeration value="long"/>
    <xs:enumeration value="ulong"/>
    <xs:enumeration value="float"/>
    <xs:enumeration value="double"/>
    <xs:enumeration value="string"/>
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="valueMapType">
  <xs:sequence>
    <xs:element name="entry" type="entryType" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attribute name="valueType" type="mapValueType" use="required"/>
</xs:complexType>

<xs:simpleType name="nameType">
  <xs:restriction base="xs:string">
    <xs:pattern value="[A-Za-z0-9_.]+"/>
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="valueType">
  <xs:attribute name="name" type="nameType" use="required"/>
  <xs:attribute name="absoluteOffset" type="xs:nonNegativeInteger"/>
  <xs:attribute name="relativeOffset" type="xs:nonNegativeInteger"/>
</xs:complexType>

<xs:complexType name="mappableValueType">
  <xs:complexContent>
    <xs:extension base="valueType">
      <xs:sequence>
        <xs:element name="valueMap" type="valueMapType" minOccurs="0"/>
      </xs:sequence>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>

<xs:complexType name="stringValueType">
  <xs:complexContent>
    <xs:extension base="mappableValueType">
      <xs:attribute name="length" type="xs:positiveInteger"/>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>

<xs:complexType name="bitLabelType">
  <xs:sequence>
    <xs:element name="valueMap" type="valueMapType" minOccurs="0"/>
  </xs:sequence>
  <xs:attribute name="name" type="nameType" use="required"/>
  <xs:attribute name="position" type="xs:nonNegativeInteger" use="required"/>
</xs:complexType>

<xs:complexType name="nbitLabelType">
  <xs:sequence>
    <xs:element name="valueMap" type="valueMapType" minOccurs="0"/>
  </xs:sequence>
  <xs:attribute name="name" type="nameType" use="required"/>
  <xs:attribute name="range" use="required">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="([0-9])+-([0-9])+"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
</xs:complexType>

<xs:complexType name="integerValueType">
  <xs:complexContent>
    <xs:extension base="mappableValueType">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="bitLabel" type="bitLabelType"/>
        <xs:element name="nbitLabel" type="nbitLabelType"/>
      </xs:choice>
      <xs:attribute name="scale" type="xs:string"/>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>

<xs:simpleType name="dimsType">
  <xs:list itemType="xs:nonNegativeInteger"/>
</xs:simpleType>

<xs:complexType name="arrayType">
  <xs:complexContent>
    <xs:extension base="valueType">
      <xs:attribute name="dims" use="required">
        <xs:simpleType>
          <xs:list itemType="xs:nonNegativeInteger"/>
        </xs:simpleType>
      </xs:attribute>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>

<xs:complexType name="skipType">
  <xs:attribute name="length" type="xs:positiveInteger"/>
</xs:complexType>

<xs:element name="binaryStream">
  <xs:complexType>
    <xs:choice minOccurs="1" maxOccurs="unbounded">

      <xs:element name="byte" type="integerValueType"/>
      <xs:element name="ubyte" type="integerValueType"/>
      <xs:element name="short" type="integerValueType"/>
      <xs:element name="ushort" type="integerValueType"/>
      <xs:element name="int" type="integerValueType"/>
      <xs:element name="uint" type="integerValueType"/>
      <xs:element name="long" type="integerValueType"/>
      <xs:element name="ulong" type="integerValueType"/>
      <xs:element name="float" type="valueType"/>
      <xs:element name="double" type="valueType"/>

      <xs:element name="byteArray" type="arrayType"/>
      <xs:element name="ubyteArray" type="arrayType"/>
      <xs:element name="shortArray" type="arrayType"/>
      <xs:element name="ushortArray" type="arrayType"/>
      <xs:element name="intArray" type="arrayType"/>
      <xs:element name="uintArray" type="arrayType"/>
      <xs:element name="longArray" type="arrayType"/>
      <xs:element name="ulongArray" type="arrayType"/>
      <xs:element name="floatArray" type="arrayType"/>
      <xs:element name="doubleArray" type="arrayType"/>

      <xs:element name="skip" type="skipType"/>

      <xs:element name="string" type="stringValueType"/>

    </xs:choice>
  </xs:complexType>
</xs:element>

</xs:schema>

=== phollemans/cwutils/resources/noaa/coastwatch/io/noaa1b/amsuaheader.xml
<?xml version="1.0"?>

<binaryStream
  xmlns="http://coastwatch.noaa.gov"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://coastwatch.noaa.gov http://coastwatch.noaa.gov/xml/binaryStream.xsd">

  <!-- File ID section -->
  <string name="creationSite" length="3">
    <valueMap valueType="string">
      <entry key="CMS" value="Centre de Meteorologie Spatiale, France"/>
      <entry key="DSS" value="Dundee Satellite Receiving Station, UK"/>
      <entry key="NSS" value="National Environmental Satellite, Data and Information Service, USA"/>
      <entry key="UKM" value="United Kingdom Meteorological Office, UK"/>
    </valueMap>
  </string>
  <skip length="1"/>
  <ushort name="formatVersion"/>
  <ushort name="formatVersionYear"/>
  <ushort name="formatVersionDay"/>
  <ushort name="headerRecords" absoluteOffset="14"/>
  <string name="datasetName" absoluteOffset="22" length="42"/> 
  <ushort name="spacecraft" absoluteOffset="72">
    <valueMap valueType="string">
      <entry key="2" value="NOAA-16"/>
      <entry key="4" value="NOAA-15"/>
      <entry key="6" value="NOAA-17"/>
      <entry key="7" value="NOAA-18"/>
      <entry key="8" value="NOAA-19"/>
    </valueMap>
  </ushort>
  <ubyte name="instrument" absoluteOffset="75">
    <valueMap valueType="string">
      <entry key="5" value="AMSU-A1 102 / AMSU-A2 103"/>
      <entry key="9" value="AMSU-A1 103 / AMSU-A2 102"/>
      <entry key="13" value="AMSU-A1 104 / AMSU-A2 104"/>
      <entry key="17" value="AMSU-A1 105 / AMSU-A2 107"/>
      <entry key="33" value="AMSU-A1 109 / AMSU-A2 105"/>
    </valueMap>
  </ubyte>
  <ushort name="dataType">
    <valueMap valueType="string">
      <entry key="10" value="AMSU-A"/>
    </valueMap>
  </ushort>
  <uint name="startDay1950" absoluteOffset="80"/>
  <ushort name="startYear"/>
  <ushort name="startDay"/>
  <uint name="startTimeUTC"/>
  <ushort name="endYear" absoluteOffset="96"/>
  <ushort name="endDay"/>
  <uint name="endTimeUTC"/>
  <short name="scanOffset" absoluteOffset="108"/>

  <!-- Dataset quality section -->
  <uint name="instrumentStatusA2" absoluteOffset="120"/>
  <uint name="instrumentStatusA1" absoluteOffset="132"/>
  <ushort name="dataRecords" absoluteOffset="144"/>
  <ushort name="calibratedScanLines"/>
  <ushort name="missingScanLines"/>
  <ushort name="dataGaps"/>
  <ushort name="dataSource" absoluteOffset="170">
    <valueMap valueType="string">
      <entry key="1" value="Fairbanks, AK"/>
      <entry key="2" value="Wallops Island, VA"/>
      <entry key="3" value="SOCC"/>
      <entry key="4" value="Svalbard, Norway"/>
      <entry key="5" value="Monterey, CA"/>
    </valueMap>
  </ushort>

  <!-- Temperature-radiance conversion section -->
  <int name="ch1CentralWave" scale="1e-6" absoluteOffset="688"/>
  <int name="ch1Constant1" scale="1e-6"/>
  <int name="ch1Constant2" scale="1e-6"/>
  <int name="ch2CentralWave" scale="1e-6"/>
  <int name="ch2Constant1" scale="1e-6"/>
  <int name="ch2Constant2" scale="1e-6"/>
  <int name="ch3CentralWave" scale="1e-6"/>
  <int name="ch3Constant1" scale="1e-6"/>
  <int name="ch3Constant2" scale="1e-6"/>
  <int name="ch4CentralWave" scale="1e-6"/>
  <int name="ch4Constant1" scale="1e-6"/>
  <int name="ch4Constant2" scale="1e-6"/>
  <int name="ch5CentralWave" scale="1e-6"/>
  <int name="ch5Constant1" scale="1e-6"/>
  <int name="ch5Constant2" scale="1e-6"/>
  <int name="ch6CentralWave" scale="1e-6"/>
  <int name="ch6Constant1" scale="1e-6"/>
  <int name="ch6Constant2" scale="1e-6"/>
  <int name="ch7CentralWave" scale="1e-6"/>
  <int name="ch7Constant1" scale="1e-6"/>
  <int name="ch7Constant2" scale="1e-6"/>
  <int name="ch8CentralWave" scale="1e-6"/>
  <int name="ch8Constant1" scale="1e-6"/>
  <int name="ch8Constant2" scale="1e-6"/>
  <int name="ch9CentralWave" scale="1e-6"/>
  <int name="ch9Constant1" scale="1e-6"/>
  <int name="ch9Constant2" scale="1e-6"/>
  <int name="ch10CentralWave" scale="1e-6"/>
  <int name="ch10Constant1" scale="1e-6"/>
  <int name="ch10Constant2" scale="1e-6"/>
  <int name="ch11CentralWave" scale="1e-6"/>
  <int name="ch11Constant1" scale="1e-6"/>
  <int name="ch11Constant2" scale="1e-6"/>
  <int name="ch12CentralWave" scale="1e-6"/>
  <int name="ch12Constant1" scale="1e-6"/>
  <int name="ch12Constant2" scale="1e-6"/>
  <int name="ch13CentralWave" scale="1e-6"/>
  <int name="ch13Constant1" scale="1e-6"/>
  <int name="ch13Constant2" scale="1e-6"/>
  <int name="ch14CentralWave" scale="1e-6"/>
  <int name="ch14Constant1" scale="1e-6"/>
  <int name="ch14Constant2" scale="1e-6"/>
  <int name="ch15CentralWave" scale="1e-6"/>
  <int name="ch15Constant1" scale="1e-6"/>
  <int name="ch15Constant2" scale="1e-6"/>
  
  <!-- Navigation section -->
  <string name="ellipsoidModel" absoluteOffset="880" length="8"/> 

</binaryStream>

=== phollemans/cwutils/resources/noaa/coastwatch/io/noaa1b/hirs4record.xml
<binaryStream
  xmlns="http://coastwatch.noaa.gov"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://coastwatch.noaa.gov http://coastwatch.noaa.gov/xml/binaryStream.xsd">

  <!-- Scan line section -->
  <ushort name="lineNumber"/>
  <ushort name="year"/>
  <ushort name="day"/>
  <uint name="timeUTC" absoluteOffset="8"/>
  <ushort name="majorFrameCount" absoluteOffset="14"/>
  <ushort name="scanPosition"/>
  <ushort name="scanType"/>

  <!-- Quality section -->
  <uint name="qualityIndicator" absoluteOffset="28">
    <bitLabel name="qualityIndicator.doNotUseScan" position="31"/>
    <bitLabel name="qualityIndicator.timeSequenceError" position="30"/>
    <bitLabel name="qualityIndicator.dataGap" position="29"/>
    <bitLabel name="qualityIndicator.calibrationAnomaly" position="28"/>
    <bitLabel name="qualityIndicator.navigationUnavailable" position="27"/>
    <bitLabel name="qualityIndicator.clockUpdated" position="26"/>
    <bitLabel name="qualityIndicator.statusChanged" position="25"/>
  </uint>
  <ubyte name="calibrationProblem" absoluteOffset="34">
    <bitLabel name="calibrationProblem.scanNotCalibrated" position="7"/>
    <bitLabel name="calibrationProblem.marginalIR" position="6"/>
    <bitLabel name="calibrationProblem.prtQualityFailed" position="5"/>
    <bitLabel name="calibrationProblem.prtMarginal" position="4"/>
    <bitLabel name="calibrationProblem.uncalibratedChannels" position="3"/>
    <bitLabel name="calibrationProblem.calibrationDisabled" position="2"/>
    <bitLabel name="calibrationProblem.lunarContamination" position="1"/>
  </ubyte>

  <!-- Calibration section -->
  <int name="ch1SecondOrder" scale="1e-12" absoluteOffset="156"/>
  <int name="ch1FirstOrder" scale="1e-9" />
  <int name="ch1ZerothOrder" scale="1e-6" />
  <int name="ch17SecondOrder" scale="1e-12"/>
  <int name="ch17FirstOrder" scale="1e-9"/>
  <int name="ch17ZerothOrder" scale="1e-6"/>
  <int name="ch2SecondOrder" scale="1e-12"/>
  <int name="ch2FirstOrder" scale="1e-9"/>
  <int name="ch2ZerothOrder" scale="1e-6"/>
  <int name="ch3SecondOrder" scale="1e-12"/>
  <int name="ch3FirstOrder" scale="1e-9"/>
  <int name="ch3ZerothOrder" scale="1e-6"/>
  <int name="ch13SecondOrder" scale="1e-12"/>
  <int name="ch13FirstOrder" scale="1e-9"/>
  <int name="ch13ZerothOrder" scale="1e-6"/>
  <int name="ch4SecondOrder" scale="1e-12"/>
  <int name="ch4FirstOrder" scale="1e-9"/>
  <int name="ch4ZerothOrder" scale="1e-6"/>
  <int name="ch18SecondOrder" scale="1e-12"/>
  <int name="ch18FirstOrder" scale="1e-9"/>
  <int name="ch18ZerothOrder" scale="1e-6"/>
  <int name="ch11SecondOrder" scale="1e-12"/>
  <int name="ch11FirstOrder" scale="1e-9"/>
  <int name="ch11ZerothOrder" scale="1e-6"/>
  <int name="ch19SecondOrder" scale="1e-12"/>
  <int name="ch19FirstOrder" scale="1e-9"/>
  <int name="ch19ZerothOrder" scale="1e-6"/>
  <int name="ch7SecondOrder" scale="1e-12"/>
  <int name="ch7FirstOrder" scale="1e-9"/>
  <int name="ch7ZerothOrder" scale="1e-6"/>
  <int name="ch8SecondOrder" scale="1e-12"/>
  <int name="ch8FirstOrder" scale="1e-9"/>
  <int name="ch8ZerothOrder" scale="1e-6"/>
  <int name="ch20SecondOrder" scale="1e-12"/>
  <int name="ch20FirstOrder" scale="1e-9"/>
  <int name="ch20ZerothOrder" scale="1e-6"/>
  <int name="ch10SecondOrder" scale="1e-12"/>
  <int name="ch10FirstOrder" scale="1e-9"/>
  <int name="ch10ZerothOrder" scale="1e-6"/>
  <int name="ch14SecondOrder" scale="1e-12"/>
  <int name="ch14FirstOrder" scale="1e-9"/>
  <int name="ch14ZerothOrder" scale="1e-6"/>
  <int name="ch6SecondOrder" scale="1e-12"/>
  <int name="ch6FirstOrder" scale="1e-9"/>
  <int name="ch6ZerothOrder" scale="1e-6"/>
  <int name="ch5SecondOrder" scale="1e-12"/>
  <int name="ch5FirstOrder" scale="1e-9"/>
  <int name="ch5ZerothOrder" scale="1e-6"/>
  <int name="ch15SecondOrder" scale="1e-12"/>
  <int name="ch15FirstOrder" scale="1e-9"/>
  <int name="ch15ZerothOrder" scale="1e-6"/>
  <int name="ch12SecondOrder" scale="1e-12"/>
  <int name="ch12FirstOrder" scale="1e-9"/>
  <int name="ch12ZerothOrder" scale="1e-6"/>
  <int name="ch16SecondOrder" scale="1e-12"/>
  <int name="ch16FirstOrder" scale="1e-9"/>
  <int name="ch16ZerothOrder" scale="1e-6"/>
  <int name="ch9SecondOrder" scale="1e-12"/>
  <int name="ch9FirstOrder" scale="1e-9"/>
  <int name="ch9ZerothOrder" scale="1e-6"/>

  <!-- Navigation section -->
  <uint name="navigationStatus" absoluteOffset="648"/>
  <shortArray name="angles" dims="168" absoluteOffset="664"/>
  <intArray name="earthLocations" dims="112" absoluteOffset="1000"/>

  <!-- HIRS data section --> 
  <shortArray name="hirsData" dims="1344" absoluteOffset="1456"/>

</binaryStream>

=== phollemans/cwutils/resources/noaa/coastwatch/io/noaa1b/mhsrecord.xml
<?xml version="1.0"?>

<binaryStream
  xmlns="http://coastwatch.noaa.gov"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://coastwatch.noaa.gov http://coastwatch.noaa.gov/xml/binaryStream.xsd">

  <!-- Scan line section -->
  <ushort name="lineNumber"/>
  <ushort name="year"/>
  <ushort name="day"/>
  <uint name="timeUTC" absoluteOffset="8"/>
  <ushort name="majorFrameCount" absoluteOffset="14"/>

  <!-- Quality section -->
  <uint name="qualityIndicator" absoluteOffset="24">
    <bitLabel name="qualityIndicator.doNotUseScan" position="31"/>
    <bitLabel name="qualityIndicator.timeSequenceError" position="30"/>
    <bitLabel name="qualityIndicator.dataGap" position="29"/>
    <bitLabel name="qualityIndicator.insufficientData" position="28"/>
    <bitLabel name="qualityIndicator.navigationUnavailable" position="27"/>
    <bitLabel name="qualityIndicator.clockUpdated" position="26"/>
    <bitLabel name="qualityIndicator.statusChanged" position="25"/>
    <bitLabel name="qualityIndicator.transmitterStatusChanged" position="4"/>
    <bitLabel name="qualityIndicator.syncError" position="3"/>
    <bitLabel name="qualityIndicator.minorFrameError" position="2"/>
    <bitLabel name="qualityIndicator.majorFrameError" position="1"/>
    <bitLabel name="qualityIndicator.parityError" position="0"/>
  </uint>
  <ushort name="calibrationProblem" absoluteOffset="29">
    <bitLabel name="calibrationProblem.scanNotCalibrated" position="7"/>
    <bitLabel name="calibrationProblem.proximityToDataGap" position="6"/>
    <bitLabel name="calibrationProblem.prtQualityFailed" position="5"/>
    <bitLabel name="calibrationProblem.prtMarginal" position="4"/>
    <bitLabel name="calibrationProblem.uncalibratedChannels" position="3"/>
    <bitLabel name="calibrationProblem.uncalibratedInstrumentMode" position="2"/>
    <bitLabel name="calibrationProblem.antennaPositionErrorSpaceView" position="1"/>
    <bitLabel name="calibrationProblem.antennaPositionErrorBlackbodyView" position="0"/>
  </ushort>
  <ushortArray name="calibrationQualityFlags" dims="5" absoluteOffset="32"/>
  
  <!-- Calibration coefficients -->
  <int name="chH1SecondOrder" scale="1e-16" absoluteOffset="60"/>
  <int name="chH1FirstOrder" scale="1e-10"/>
  <int name="chH1ZerothOrder" scale="1e-6"/>
  <int name="chH2SecondOrder" scale="1e-16"/>
  <int name="chH2FirstOrder" scale="1e-10"/>
  <int name="chH2ZerothOrder" scale="1e-6"/>
  <int name="chH3SecondOrder" scale="1e-16"/>
  <int name="chH3FirstOrder" scale="1e-10"/>
  <int name="chH3ZerothOrder" scale="1e-6"/>
  <int name="chH4SecondOrder" scale="1e-16"/>
  <int name="chH4FirstOrder" scale="1e-10"/>
  <int name="chH4ZerothOrder" scale="1e-6"/>
  <int name="chH5SecondOrder" scale="1e-16"/>
  <int name="chH5FirstOrder" scale="1e-10"/>
  <int name="chH5ZerothOrder" scale="1e-6"/>

  <!-- Navigation section -->
  <uint name="navigationStatus" absoluteOffset="196"/>
  <shortArray name="angles" dims="270" absoluteOffset="212"/>
  <intArray name="earthLocations" dims="180" absoluteOffset="752"/>

  <!-- MHS sensor data -->
  <ushortArray name="mhsData" dims="540" absoluteOffset="1480"/>

</binaryStream>

=== phollemans/cwutils/resources/noaa/coastwatch/io/noaa1b/arsheader.xml
<?xml version="1.0"?>

<binaryStream
  xmlns="http://coastwatch.noaa.gov"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://coastwatch.noaa.gov http://coastwatch.noaa.gov/xml/binaryStream.xsd">

  <!-- Top section -->
  <string name="processingSite" length="1" absoluteOffset="21">
    <valueMap valueType="string">
      <entry key="A" value="CLASS"/>
      <entry key="B" value="NCDC/Suitland"/>
      <entry key="C" value="NCDC/Asheville"/>
    </valueMap>
  </string>
  <string name="processingSoftware" length="8"/>
  <string name="datasetName" length="42"/>
  
  <!-- Dataset selection section -->
  <string name="sensorDataWordSize" length="2" absoluteOffset="117"/>

  <!-- Dataset summary section -->
  <string name="firstLatitude" length="3" absoluteOffset="147"/>
  <string name="lastLatitude" length="3"/>
  <string name="firstLongitude" length="4"/>
  <string name="lastLongitude" length="4"/>
  <string name="dataFormat" length="20"/>
  <string name="recordSize" length="6"/>
  <string name="numRecords" length="6"/>

</binaryStream>
