=== phollemans/cwutils/resources/noaa/coastwatch/render/colorlookup.dtd
<!-- 

     File: colorlookup.dtd
   Author: Peter Hollemans
     Date: 2004/05/17

  CoastWatch Software Library and Utilities
  Copyright (c) 2004 National Oceanic and Atmospheric Administration
  All rights reserved.

  Developed by: CoastWatch / OceanWatch
                Center for Satellite Applications and Research
                http://coastwatch.noaa.gov

  For conditions of distribution and use, see the accompanying
  license.txt file.

-->

<!ELEMENT colorlookup (color*)>
<!ELEMENT color EMPTY>
<!ATTLIST color name CDATA #REQUIRED>
<!ATTLIST color r CDATA #REQUIRED>
<!ATTLIST color g CDATA #REQUIRED>
<!ATTLIST color b CDATA #REQUIRED>

=== phollemans/cwutils/resources/noaa/coastwatch/render/rgb.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE colorlookup SYSTEM "http://coastwatch.noaa.gov/xml/colorlookup.dtd">

<!-- This file was derived from the X11R6 rgb.txt on RedHat 7.2 -->

<colorlookup>
  <color name="snow" r="255" g="250" b="250" />
  <color name="ghost white" r="248" g="248" b="255" />
  <color name="GhostWhite" r="248" g="248" b="255" />
  <color name="white smoke" r="245" g="245" b="245" />
  <color name="WhiteSmoke" r="245" g="245" b="245" />
  <color name="gainsboro" r="220" g="220" b="220" />
  <color name="floral white" r="255" g="250" b="240" />
  <color name="FloralWhite" r="255" g="250" b="240" />
  <color name="old lace" r="253" g="245" b="230" />
  <color name="OldLace" r="253" g="245" b="230" />
  <color name="linen" r="250" g="240" b="230" />
  <color name="antique white" r="250" g="235" b="215" />
  <color name="AntiqueWhite" r="250" g="235" b="215" />
  <color name="papaya whip" r="255" g="239" b="213" />
  <color name="PapayaWhip" r="255" g="239" b="213" />
  <color name="blanched almond" r="255" g="235" b="205" />
  <color name="BlanchedAlmond" r="255" g="235" b="205" />
  <color name="bisque" r="255" g="228" b="196" />
  <color name="peach puff" r="255" g="218" b="185" />
  <color name="PeachPuff" r="255" g="218" b="185" />
  <color name="navajo white" r="255" g="222" b="173" />
  <color name="NavajoWhite" r="255" g="222" b="173" />
  <color name="moccasin" r="255" g="228" b="181" />
  <color name="cornsilk" r="255" g="248" b="220" />
  <color name="ivory" r="255" g="255" b="240" />
  <color name="lemon chiffon" r="255" g="250" b="205" />
  <color name="LemonChiffon" r="255" g="250" b="205" />
  <color name="seashell" r="255" g="245" b="238" />
  <color name="honeydew" r="240" g="255" b="240" />
  <color name="mint cream" r="245" g="255" b="250" />
  <color name="MintCream" r="245" g="255" b="250" />
  <color name="azure" r="240" g="255" b="255" />
  <color name="alice blue" r="240" g="248" b="255" />
  <color name="AliceBlue" r="240" g="248" b="255" />
  <color name="lavender" r="230" g="230" b="250" />
  <color name="lavender blush" r="255" g="240" b="245" />
  <color name="LavenderBlush" r="255" g="240" b="245" />
  <color name="misty rose" r="255" g="228" b="225" />
  <color name="MistyRose" r="255" g="228" b="225" />
  <color name="white" r="255" g="255" b="255" />
  <color name="black" r="0" g="0" b="0" />
  <color name="dark slate gray" r="47" g="79" b="79" />
  <color name="DarkSlateGray" r="47" g="79" b="79" />
  <color name="dark slate grey" r="47" g="79" b="79" />
  <color name="DarkSlateGrey" r="47" g="79" b="79" />
  <color name="dim gray" r="105" g="105" b="105" />
  <color name="DimGray" r="105" g="105" b="105" />
  <color name="dim grey" r="105" g="105" b="105" />
  <color name="DimGrey" r="105" g="105" b="105" />
  <color name="slate gray" r="112" g="128" b="144" />
  <color name="SlateGray" r="112" g="128" b="144" />
  <color name="slate grey" r="112" g="128" b="144" />
  <color name="SlateGrey" r="112" g="128" b="144" />
  <color name="light slate gray" r="119" g="136" b="153" />
  <color name="LightSlateGray" r="119" g="136" b="153" />
  <color name="light slate grey" r="119" g="136" b="153" />
  <color name="LightSlateGrey" r="119" g="136" b="153" />
  <color name="gray" r="190" g="190" b="190" />
  <color name="grey" r="190" g="190" b="190" />
  <color name="light grey" r="211" g="211" b="211" />
  <color name="LightGrey" r="211" g="211" b="211" />
  <color name="light gray" r="211" g="211" b="211" />
  <color name="LightGray" r="211" g="211" b="211" />
  <color name="midnight blue" r="25" g="25" b="112" />
  <color name="MidnightBlue" r="25" g="25" b="112" />
  <color name="navy" r="0" g="0" b="128" />
  <color name="navy blue" r="0" g="0" b="128" />
  <color name="NavyBlue" r="0" g="0" b="128" />
  <color name="cornflower blue" r="100" g="149" b="237" />
  <color name="CornflowerBlue" r="100" g="149" b="237" />
  <color name="dark slate blue" r="72" g="61" b="139" />
  <color name="DarkSlateBlue" r="72" g="61" b="139" />
  <color name="slate blue" r="106" g="90" b="205" />
  <color name="SlateBlue" r="106" g="90" b="205" />
  <color name="medium slate blue" r="123" g="104" b="238" />
  <color name="MediumSlateBlue" r="123" g="104" b="238" />
  <color name="light slate blue" r="132" g="112" b="255" />
  <color name="LightSlateBlue" r="132" g="112" b="255" />
  <color name="medium blue" r="0" g="0" b="205" />
  <color name="MediumBlue" r="0" g="0" b="205" />
  <color name="royal blue" r="65" g="105" b="225" />
  <color name="RoyalBlue" r="65" g="105" b="225" />
  <color name="blue" r="0" g="0" b="255" />
  <color name="dodger blue" r="30" g="144" b="255" />
  <color name="DodgerBlue" r="30" g="144" b="255" />
  <color name="deep sky blue" r="0" g="191" b="255" />
  <color name="DeepSkyBlue" r="0" g="191" b="255" />
  <color name="sky blue" r="135" g="206" b="235" />
  <color name="SkyBlue" r="135" g="206" b="235" />
  <color name="light sky blue" r="135" g="206" b="250" />
  <color name="LightSkyBlue" r="135" g="206" b="250" />
  <color name="steel blue" r="70" g="130" b="180" />
  <color name="SteelBlue" r="70" g="130" b="180" />
  <color name="light steel blue" r="176" g="196" b="222" />
  <color name="LightSteelBlue" r="176" g="196" b="222" />
  <color name="light blue" r="173" g="216" b="230" />
  <color name="LightBlue" r="173" g="216" b="230" />
  <color name="powder blue" r="176" g="224" b="230" />
  <color name="PowderBlue" r="176" g="224" b="230" />
  <color name="pale turquoise" r="175" g="238" b="238" />
  <color name="PaleTurquoise" r="175" g="238" b="238" />
  <color name="dark turquoise" r="0" g="206" b="209" />
  <color name="DarkTurquoise" r="0" g="206" b="209" />
  <color name="medium turquoise" r="72" g="209" b="204" />
  <color name="MediumTurquoise" r="72" g="209" b="204" />
  <color name="turquoise" r="64" g="224" b="208" />
  <color name="cyan" r="0" g="255" b="255" />
  <color name="light cyan" r="224" g="255" b="255" />
  <color name="LightCyan" r="224" g="255" b="255" />
  <color name="cadet blue" r="95" g="158" b="160" />
  <color name="CadetBlue" r="95" g="158" b="160" />
  <color name="medium aquamarine" r="102" g="205" b="170" />
  <color name="MediumAquamarine" r="102" g="205" b="170" />
  <color name="aquamarine" r="127" g="255" b="212" />
  <color name="dark green" r="0" g="100" b="0" />
  <color name="DarkGreen" r="0" g="100" b="0" />
  <color name="dark olive green" r="85" g="107" b="47" />
  <color name="DarkOliveGreen" r="85" g="107" b="47" />
  <color name="dark sea green" r="143" g="188" b="143" />
  <color name="DarkSeaGreen" r="143" g="188" b="143" />
  <color name="sea green" r="46" g="139" b="87" />
  <color name="SeaGreen" r="46" g="139" b="87" />
  <color name="medium sea green" r="60" g="179" b="113" />
  <color name="MediumSeaGreen" r="60" g="179" b="113" />
  <color name="light sea green" r="32" g="178" b="170" />
  <color name="LightSeaGreen" r="32" g="178" b="170" />
  <color name="pale green" r="152" g="251" b="152" />
  <color name="PaleGreen" r="152" g="251" b="152" />
  <color name="spring green" r="0" g="255" b="127" />
  <color name="SpringGreen" r="0" g="255" b="127" />
  <color name="lawn green" r="124" g="252" b="0" />
  <color name="LawnGreen" r="124" g="252" b="0" />
  <color name="green" r="0" g="255" b="0" />
  <color name="chartreuse" r="127" g="255" b="0" />
  <color name="medium spring green" r="0" g="250" b="154" />
  <color name="MediumSpringGreen" r="0" g="250" b="154" />
  <color name="green yellow" r="173" g="255" b="47" />
  <color name="GreenYellow" r="173" g="255" b="47" />
  <color name="lime green" r="50" g="205" b="50" />
  <color name="LimeGreen" r="50" g="205" b="50" />
  <color name="yellow green" r="154" g="205" b="50" />
  <color name="YellowGreen" r="154" g="205" b="50" />
  <color name="forest green" r="34" g="139" b="34" />
  <color name="ForestGreen" r="34" g="139" b="34" />
  <color name="olive drab" r="107" g="142" b="35" />
  <color name="OliveDrab" r="107" g="142" b="35" />
  <color name="dark khaki" r="189" g="183" b="107" />
  <color name="DarkKhaki" r="189" g="183" b="107" />
  <color name="khaki" r="240" g="230" b="140" />
  <color name="pale goldenrod" r="238" g="232" b="170" />
  <color name="PaleGoldenrod" r="238" g="232" b="170" />
  <color name="light goldenrod yellow" r="250" g="250" b="210" />
  <color name="LightGoldenrodYellow" r="250" g="250" b="210" />
  <color name="light yellow" r="255" g="255" b="224" />
  <color name="LightYellow" r="255" g="255" b="224" />
  <color name="yellow" r="255" g="255" b="0" />
  <color name="gold" r="255" g="215" b="0" />
  <color name="light goldenrod" r="238" g="221" b="130" />
  <color name="LightGoldenrod" r="238" g="221" b="130" />
  <color name="goldenrod" r="218" g="165" b="32" />
  <color name="dark goldenrod" r="184" g="134" b="11" />
  <color name="DarkGoldenrod" r="184" g="134" b="11" />
  <color name="rosy brown" r="188" g="143" b="143" />
  <color name="RosyBrown" r="188" g="143" b="143" />
  <color name="indian red" r="205" g="92" b="92" />
  <color name="IndianRed" r="205" g="92" b="92" />
  <color name="saddle brown" r="139" g="69" b="19" />
  <color name="SaddleBrown" r="139" g="69" b="19" />
  <color name="sienna" r="160" g="82" b="45" />
  <color name="peru" r="205" g="133" b="63" />
  <color name="burlywood" r="222" g="184" b="135" />
  <color name="beige" r="245" g="245" b="220" />
  <color name="wheat" r="245" g="222" b="179" />
  <color name="sandy brown" r="244" g="164" b="96" />
  <color name="SandyBrown" r="244" g="164" b="96" />
  <color name="tan" r="210" g="180" b="140" />
  <color name="chocolate" r="210" g="105" b="30" />
  <color name="firebrick" r="178" g="34" b="34" />
  <color name="brown" r="165" g="42" b="42" />
  <color name="dark salmon" r="233" g="150" b="122" />
  <color name="DarkSalmon" r="233" g="150" b="122" />
  <color name="salmon" r="250" g="128" b="114" />
