=== phollemans/cwutils/resources/noaa/coastwatch/render/palette.dtd
<!-- 

     FILE: palette.dtd
  PURPOSE: Defines the CoastWatch palette structure in XML.
   AUTHOR: Peter Hollemans
     DATE: 2004/05/16

  CoastWatch Software Library and Utilities
  Copyright 2004, USDOC/NOAA/NESDIS CoastWatch

-->

<!ELEMENT palette (color*)>
<!ATTLIST palette name CDATA #REQUIRED>
<!ATTLIST palette length CDATA #REQUIRED>
<!ELEMENT color EMPTY>
<!ATTLIST color r CDATA #REQUIRED>
<!ATTLIST color g CDATA #REQUIRED>
<!ATTLIST color b CDATA #REQUIRED>

=== phollemans/cwutils/resources/noaa/coastwatch/render/Green-White-Linear.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE palette SYSTEM "http://coastwatch.noaa.gov/xml/palette.dtd">

<!-- This file was generated using data from the RSI IDL package v5.4 -->

<palette name="Green-White-Linear" length="256">
  <color r="0" g="0" b="0" />
  <color r="0" g="1" b="0" />
  <color r="0" g="2" b="0" />
  <color r="0" g="3" b="0" />
  <color r="0" g="4" b="0" />
  <color r="0" g="5" b="0" />
  <color r="0" g="6" b="0" />
  <color r="0" g="7" b="0" />
  <color r="0" g="8" b="0" />
  <color r="0" g="9" b="0" />
  <color r="0" g="10" b="0" />
  <color r="0" g="11" b="0" />
  <color r="0" g="12" b="0" />
  <color r="0" g="13" b="0" />
  <color r="0" g="14" b="0" />
  <color r="0" g="15" b="0" />
  <color r="0" g="16" b="0" />
  <color r="0" g="17" b="0" />
  <color r="0" g="18" b="0" />
  <color r="0" g="19" b="0" />
  <color r="0" g="20" b="0" />
  <color r="0" g="21" b="0" />
  <color r="0" g="22" b="0" />
  <color r="0" g="23" b="0" />
  <color r="0" g="24" b="0" />
  <color r="0" g="25" b="0" />
  <color r="0" g="26" b="0" />
  <color r="0" g="27" b="0" />
  <color r="0" g="28" b="0" />
  <color r="0" g="29" b="0" />
  <color r="0" g="30" b="0" />
  <color r="0" g="31" b="0" />
  <color r="0" g="32" b="0" />
  <color r="0" g="33" b="0" />
  <color r="0" g="34" b="0" />
  <color r="0" g="35" b="0" />
  <color r="0" g="36" b="0" />
  <color r="0" g="37" b="0" />
  <color r="0" g="38" b="0" />
  <color r="0" g="39" b="0" />
  <color r="0" g="40" b="0" />
  <color r="0" g="41" b="0" />
  <color r="0" g="42" b="0" />
  <color r="0" g="43" b="0" />
  <color r="0" g="44" b="0" />
  <color r="0" g="45" b="0" />
  <color r="0" g="46" b="0" />
  <color r="0" g="47" b="0" />
  <color r="0" g="48" b="0" />
  <color r="0" g="49" b="0" />
  <color r="0" g="50" b="0" />
  <color r="0" g="51" b="0" />
  <color r="0" g="52" b="0" />
  <color r="0" g="53" b="0" />
  <color r="0" g="54" b="0" />
  <color r="0" g="55" b="0" />
  <color r="0" g="56" b="0" />
  <color r="0" g="57" b="0" />
  <color r="0" g="58" b="0" />
  <color r="0" g="59" b="0" />
  <color r="0" g="60" b="0" />
  <color r="0" g="61" b="0" />
  <color r="0" g="62" b="0" />
  <color r="0" g="63" b="0" />
  <color r="0" g="64" b="0" />
  <color r="0" g="65" b="0" />
  <color r="0" g="66" b="0" />
  <color r="0" g="67" b="0" />
  <color r="0" g="68" b="0" />
  <color r="0" g="69" b="0" />
  <color r="0" g="70" b="0" />
  <color r="0" g="71" b="0" />
  <color r="0" g="72" b="0" />
  <color r="0" g="73" b="0" />
  <color r="0" g="74" b="0" />
  <color r="0" g="75" b="0" />
  <color r="0" g="76" b="0" />
  <color r="0" g="77" b="0" />
  <color r="0" g="78" b="0" />
  <color r="0" g="79" b="0" />
  <color r="0" g="80" b="0" />
  <color r="0" g="81" b="0" />
  <color r="0" g="82" b="0" />
  <color r="0" g="83" b="0" />
  <color r="0" g="84" b="0" />
  <color r="0" g="85" b="0" />
  <color r="0" g="86" b="0" />
  <color r="0" g="87" b="0" />
  <color r="0" g="88" b="0" />
  <color r="0" g="89" b="0" />
  <color r="0" g="90" b="0" />
  <color r="0" g="91" b="0" />
  <color r="0" g="92" b="0" />
  <color r="0" g="93" b="0" />
  <color r="0" g="94" b="0" />
  <color r="0" g="95" b="0" />
  <color r="0" g="96" b="0" />
  <color r="0" g="97" b="0" />
  <color r="1" g="98" b="0" />
  <color r="3" g="99" b="0" />
  <color r="4" g="100" b="0" />
  <color r="6" g="101" b="0" />
  <color r="8" g="102" b="0" />
  <color r="9" g="103" b="0" />
  <color r="11" g="104" b="0" />
  <color r="12" g="105" b="0" />
  <color r="14" g="106" b="0" />
  <color r="16" g="107" b="0" />
  <color r="17" g="108" b="0" />
  <color r="19" g="109" b="0" />
  <color r="20" g="110" b="0" />
  <color r="22" g="111" b="0" />
  <color r="24" g="112" b="0" />
  <color r="25" g="113" b="0" />
  <color r="27" g="114" b="0" />
  <color r="29" g="115" b="0" />
  <color r="30" g="116" b="0" />
  <color r="32" g="117" b="0" />
  <color r="33" g="118" b="0" />
  <color r="35" g="119" b="0" />
  <color r="37" g="120" b="0" />
  <color r="38" g="121" b="0" />
  <color r="40" g="122" b="0" />
  <color r="41" g="123" b="0" />
  <color r="43" g="124" b="0" />
  <color r="45" g="125" b="0" />
  <color r="46" g="126" b="0" />
  <color r="48" g="127" b="0" />
  <color r="50" g="128" b="0" />
  <color r="51" g="129" b="0" />
  <color r="53" g="130" b="0" />
  <color r="54" g="131" b="0" />
  <color r="56" g="132" b="0" />
  <color r="58" g="133" b="0" />
  <color r="59" g="134" b="0" />
  <color r="61" g="135" b="0" />
  <color r="62" g="136" b="0" />
  <color r="64" g="137" b="0" />
  <color r="66" g="138" b="0" />
  <color r="67" g="139" b="0" />
  <color r="69" g="140" b="0" />
  <color r="71" g="141" b="0" />
  <color r="72" g="142" b="0" />
  <color r="74" g="143" b="0" />
  <color r="75" g="144" b="0" />
  <color r="77" g="145" b="0" />
  <color r="79" g="146" b="0" />
  <color r="80" g="147" b="0" />
  <color r="82" g="148" b="0" />
  <color r="83" g="149" b="0" />
  <color r="85" g="150" b="0" />
  <color r="87" g="151" b="0" />
  <color r="88" g="152" b="0" />
  <color r="90" g="153" b="0" />
  <color r="91" g="154" b="0" />
  <color r="93" g="155" b="0" />
  <color r="95" g="156" b="0" />
  <color r="96" g="157" b="0" />
  <color r="98" g="158" b="0" />
  <color r="100" g="159" b="0" />
  <color r="101" g="160" b="0" />
  <color r="103" g="161" b="0" />
  <color r="104" g="162" b="0" />
  <color r="106" g="163" b="0" />
  <color r="108" g="164" b="0" />
  <color r="109" g="165" b="0" />
  <color r="111" g="166" b="0" />
  <color r="112" g="167" b="0" />
  <color r="114" g="168" b="0" />
  <color r="116" g="169" b="0" />
  <color r="117" g="170" b="0" />
  <color r="119" g="171" b="0" />
  <color r="121" g="172" b="0" />
  <color r="122" g="173" b="0" />
  <color r="124" g="174" b="0" />
  <color r="125" g="175" b="0" />
  <color r="127" g="176" b="0" />
  <color r="129" g="177" b="0" />
  <color r="130" g="178" b="0" />
  <color r="132" g="179" b="0" />
  <color r="133" g="180" b="0" />
  <color r="135" g="181" b="0" />
  <color r="137" g="182" b="3" />
  <color r="138" g="183" b="6" />
  <color r="140" g="184" b="10" />
  <color r="142" g="185" b="13" />
  <color r="143" g="186" b="17" />
  <color r="145" g="187" b="20" />
  <color r="146" g="188" b="24" />
  <color r="148" g="189" b="27" />
  <color r="150" g="190" b="31" />
  <color r="151" g="191" b="34" />
  <color r="153" g="192" b="37" />
  <color r="154" g="193" b="41" />
  <color r="156" g="194" b="44" />
  <color r="158" g="195" b="48" />
  <color r="159" g="196" b="51" />
  <color r="161" g="197" b="55" />
  <color r="163" g="198" b="58" />
  <color r="164" g="199" b="62" />
  <color r="166" g="200" b="65" />
  <color r="167" g="201" b="68" />
  <color r="169" g="202" b="72" />
  <color r="171" g="203" b="75" />
  <color r="172" g="204" b="79" />
  <color r="174" g="205" b="82" />
  <color r="175" g="206" b="86" />
  <color r="177" g="207" b="89" />
  <color r="179" g="208" b="93" />
  <color r="180" g="209" b="96" />
  <color r="182" g="210" b="99" />
  <color r="183" g="211" b="103" />
  <color r="185" g="212" b="106" />
  <color r="187" g="213" b="110" />
  <color r="188" g="214" b="113" />
  <color r="190" g="215" b="117" />
  <color r="192" g="216" b="120" />
  <color r="193" g="217" b="124" />
  <color r="195" g="218" b="127" />
  <color r="196" g="219" b="130" />
  <color r="198" g="220" b="134" />
  <color r="200" g="221" b="137" />
  <color r="201" g="222" b="141" />
  <color r="203" g="223" b="144" />
  <color r="204" g="224" b="148" />
  <color r="206" g="225" b="151" />
  <color r="208" g="226" b="155" />
  <color r="209" g="227" b="158" />
  <color r="211" g="228" b="161" />
  <color r="213" g="229" b="165" />
  <color r="214" g="230" b="168" />
  <color r="216" g="231" b="172" />
  <color r="217" g="232" b="175" />
  <color r="219" g="233" b="179" />
  <color r="221" g="234" b="182" />
  <color r="222" g="235" b="186" />
  <color r="224" g="236" b="189" />
  <color r="225" g="237" b="192" />
  <color r="227" g="238" b="196" />
  <color r="229" g="239" b="199" />
  <color r="230" g="240" b="203" />
  <color r="232" g="241" b="206" />
  <color r="234" g="242" b="210" />
  <color r="235" g="243" b="213" />
  <color r="237" g="244" b="217" />
  <color r="238" g="245" b="220" />
  <color r="240" g="246" b="223" />
  <color r="242" g="247" b="227" />
  <color r="243" g="248" b="230" />
  <color r="245" g="249" b="234" />
  <color r="246" g="250" b="237" />
  <color r="248" g="251" b="241" />
  <color r="250" g="252" b="244" />
  <color r="251" g="253" b="248" />
  <color r="253" g="254" b="251" />
  <color r="255" g="255" b="255" />
</palette>

=== phollemans/cwutils/resources/noaa/coastwatch/render/Blue-Green-Red-Yellow.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE palette SYSTEM "http://coastwatch.noaa.gov/xml/palette.dtd">

<!-- This file was generated using data from the RSI IDL package v5.4 -->

<palette name="Blue-Green-Red-Yellow" length="256">
  <color r="0" g="0" b="0" />
  <color r="0" g="0" b="2" />
  <color r="0" g="0" b="4" />
  <color r="0" g="0" b="6" />
  <color r="0" g="0" b="8" />
  <color r="0" g="0" b="10" />
  <color r="0" g="0" b="12" />
  <color r="0" g="0" b="14" />
  <color r="0" g="0" b="16" />
  <color r="0" g="0" b="18" />
  <color r="0" g="0" b="20" />
  <color r="0" g="0" b="22" />
  <color r="0" g="0" b="25" />
  <color r="0" g="0" b="27" />
  <color r="0" g="0" b="29" />
  <color r="0" g="0" b="31" />
  <color r="0" g="0" b="33" />
  <color r="0" g="0" b="35" />
  <color r="0" g="0" b="37" />
  <color r="0" g="0" b="39" />
  <color r="0" g="0" b="41" />
  <color r="0" g="0" b="43" />
  <color r="0" g="0" b="45" />
  <color r="0" g="0" b="47" />
  <color r="0" g="0" b="50" />
  <color r="0" g="0" b="52" />
  <color r="0" g="0" b="54" />
  <color r="0" g="0" b="56" />
  <color r="0" g="0" b="58" />
  <color r="0" g="0" b="60" />
  <color r="0" g="0" b="62" />
  <color r="0" g="0" b="64" />
  <color r="0" g="0" b="66" />
  <color r="0" g="3" b="68" />
  <color r="0" g="6" b="70" />
  <color r="0" g="9" b="72" />
  <color r="0" g="12" b="75" />
  <color r="0" g="15" b="77" />
  <color r="0" g="18" b="79" />
  <color r="0" g="21" b="81" />
  <color r="0" g="25" b="83" />
  <color r="0" g="28" b="85" />
  <color r="0" g="31" b="87" />
  <color r="0" g="34" b="89" />
  <color r="0" g="37" b="91" />
  <color r="0" g="40" b="93" />
  <color r="0" g="43" b="95" />
  <color r="0" g="46" b="97" />
  <color r="0" g="50" b="100" />
  <color r="0" g="53" b="100" />
  <color r="0" g="56" b="100" />
  <color r="0" g="59" b="100" />
  <color r="0" g="62" b="100" />
  <color r="0" g="65" b="100" />
  <color r="0" g="68" b="100" />
  <color r="0" g="71" b="100" />
  <color r="0" g="75" b="100" />
  <color r="0" g="78" b="100" />
  <color r="0" g="81" b="100" />
  <color r="0" g="84" b="100" />
  <color r="0" g="87" b="100" />
  <color r="0" g="90" b="100" />
  <color r="0" g="93" b="100" />
  <color r="0" g="96" b="100" />
  <color r="0" g="100" b="100" />
  <color r="0" g="103" b="100" />
  <color r="0" g="106" b="100" />
  <color r="0" g="109" b="100" />
  <color r="0" g="112" b="100" />
  <color r="0" g="115" b="100" />
  <color r="0" g="118" b="100" />
  <color r="0" g="121" b="100" />
  <color r="0" g="125" b="100" />
  <color r="0" g="128" b="100" />
  <color r="0" g="131" b="100" />
  <color r="0" g="134" b="100" />
  <color r="0" g="137" b="100" />
  <color r="0" g="140" b="100" />
  <color r="0" g="143" b="100" />
  <color r="0" g="146" b="100" />
  <color r="0" g="150" b="100" />
  <color r="0" g="150" b="96" />
  <color r="0" g="150" b="93" />
  <color r="0" g="150" b="90" />
  <color r="0" g="150" b="87" />
  <color r="0" g="150" b="84" />
  <color r="0" g="150" b="81" />
  <color r="0" g="150" b="78" />
  <color r="0" g="150" b="75" />
  <color r="0" g="150" b="71" />
  <color r="0" g="150" b="68" />
  <color r="0" g="150" b="65" />
  <color r="0" g="150" b="62" />
  <color r="0" g="150" b="59" />
  <color r="0" g="150" b="56" />
  <color r="0" g="150" b="53" />
  <color r="0" g="150" b="50" />
  <color r="0" g="149" b="46" />
  <color r="0" g="148" b="43" />
  <color r="0" g="148" b="40" />
  <color r="0" g="147" b="37" />
  <color r="0" g="146" b="34" />
  <color r="0" g="146" b="31" />
  <color r="0" g="145" b="28" />
  <color r="0" g="145" b="25" />
  <color r="0" g="144" b="21" />
  <color r="0" g="143" b="18" />
  <color r="0" g="143" b="15" />
  <color r="0" g="142" b="12" />
  <color r="0" g="141" b="9" />
  <color r="0" g="141" b="6" />
  <color r="0" g="140" b="3" />
  <color r="0" g="140" b="0" />
  <color r="7" g="137" b="0" />
  <color r="15" g="135" b="0" />
  <color r="22" g="132" b="0" />
  <color r="30" g="130" b="0" />
  <color r="37" g="127" b="0" />
  <color r="45" g="125" b="0" />
  <color r="52" g="122" b="0" />
  <color r="60" g="120" b="0" />
  <color r="67" g="117" b="0" />
  <color r="75" g="115" b="0" />
  <color r="82" g="112" b="0" />
  <color r="90" g="110" b="0" />
  <color r="97" g="107" b="0" />
  <color r="105" g="105" b="0" />
  <color r="112" g="102" b="0" />
  <color r="120" g="100" b="0" />
  <color r="125" g="93" b="0" />
  <color r="130" g="87" b="0" />
  <color r="135" g="81" b="0" />
  <color r="140" g="75" b="0" />
  <color r="145" g="68" b="0" />
  <color r="150" g="62" b="0" />
  <color r="155" g="56" b="0" />
  <color r="160" g="50" b="0" />
  <color r="165" g="43" b="0" />
  <color r="170" g="37" b="0" />
  <color r="175" g="31" b="0" />
  <color r="180" g="25" b="0" />
  <color r="185" g="18" b="0" />
  <color r="190" g="12" b="0" />
  <color r="195" g="6" b="0" />
  <color r="200" g="0" b="0" />
  <color r="200" g="2" b="0" />
  <color r="201" g="4" b="0" />
  <color r="201" g="6" b="0" />
  <color r="202" g="9" b="0" />
  <color r="202" g="11" b="0" />
  <color r="203" g="13" b="0" />
  <color r="203" g="16" b="0" />
  <color r="204" g="18" b="0" />
  <color r="204" g="20" b="0" />
  <color r="205" g="23" b="0" />
  <color r="205" g="25" b="0" />
  <color r="206" g="27" b="0" />
  <color r="206" g="29" b="0" />
  <color r="207" g="32" b="0" />
  <color r="207" g="34" b="0" />
  <color r="208" g="36" b="0" />
  <color r="208" g="39" b="0" />
  <color r="209" g="41" b="0" />
  <color r="209" g="43" b="0" />
  <color r="210" g="46" b="0" />
  <color r="210" g="48" b="0" />
  <color r="211" g="50" b="0" />
  <color r="211" g="53" b="0" />
  <color r="212" g="55" b="0" />
  <color r="212" g="57" b="0" />
  <color r="213" g="59" b="0" />
  <color r="213" g="62" b="0" />
  <color r="214" g="64" b="0" />
  <color r="214" g="66" b="0" />
  <color r="215" g="69" b="0" />
  <color r="215" g="71" b="0" />
  <color r="216" g="73" b="0" />
  <color r="216" g="76" b="0" />
  <color r="217" g="78" b="0" />
  <color r="217" g="80" b="0" />
  <color r="218" g="83" b="0" />
  <color r="218" g="85" b="0" />
  <color r="219" g="87" b="0" />
  <color r="219" g="89" b="0" />
  <color r="220" g="92" b="0" />
  <color r="220" g="94" b="0" />
  <color r="221" g="96" b="0" />
  <color r="221" g="99" b="0" />
  <color r="222" g="101" b="0" />
  <color r="222" g="103" b="0" />
  <color r="223" g="106" b="0" />
  <color r="223" g="108" b="0" />
  <color r="224" g="110" b="0" />
  <color r="224" g="113" b="0" />
  <color r="225" g="115" b="0" />
  <color r="225" g="117" b="0" />
  <color r="226" g="119" b="0" />
  <color r="226" g="122" b="0" />
  <color r="227" g="124" b="0" />
  <color r="227" g="126" b="0" />
  <color r="228" g="129" b="0" />
  <color r="228" g="131" b="0" />
  <color r="229" g="133" b="0" />
  <color r="229" g="136" b="0" />
  <color r="230" g="138" b="0" />
  <color r="230" g="140" b="0" />
  <color r="231" g="142" b="0" />
  <color r="231" g="145" b="0" />
  <color r="232" g="147" b="0" />
  <color r="232" g="149" b="0" />
  <color r="233" g="152" b="0" />
  <color r="233" g="154" b="0" />
  <color r="234" g="156" b="0" />
  <color r="234" g="159" b="0" />
  <color r="235" g="161" b="0" />
  <color r="235" g="163" b="0" />
  <color r="236" g="166" b="0" />
  <color r="236" g="168" b="0" />
  <color r="237" g="170" b="0" />
  <color r="237" g="172" b="0" />
  <color r="238" g="175" b="0" />
  <color r="238" g="177" b="0" />
  <color r="239" g="179" b="0" />
  <color r="239" g="182" b="0" />
  <color r="240" g="184" b="0" />
  <color r="240" g="186" b="0" />
  <color r="241" g="189" b="0" />
  <color r="241" g="191" b="0" />
  <color r="242" g="193" b="0" />
  <color r="242" g="196" b="0" />
  <color r="243" g="198" b="0" />
  <color r="243" g="200" b="0" />
  <color r="244" g="202" b="0" />
  <color r="244" g="205" b="0" />
  <color r="245" g="207" b="0" />
  <color r="245" g="209" b="0" />
  <color r="246" g="212" b="0" />
  <color r="246" g="214" b="0" />
  <color r="247" g="216" b="0" />
  <color r="247" g="219" b="0" />
  <color r="248" g="221" b="0" />
  <color r="248" g="223" b="0" />
  <color r="249" g="226" b="0" />
  <color r="249" g="228" b="0" />
  <color r="250" g="230" b="0" />
  <color r="250" g="232" b="0" />
  <color r="251" g="235" b="0" />
  <color r="251" g="237" b="0" />
  <color r="252" g="239" b="0" />
  <color r="252" g="242" b="0" />
  <color r="253" g="244" b="0" />
  <color r="253" g="246" b="0" />
  <color r="254" g="249" b="0" />
  <color r="254" g="251" b="0" />
  <color r="255" g="253" b="0" />
  <color r="255" g="255" b="0" />
</palette>

=== phollemans/cwutils/resources/noaa/coastwatch/render/HSB-Cycle.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE palette SYSTEM "http://coastwatch.noaa.gov/xml/palette.dtd">

<palette name="HSB-Cycle" length="256">
  <color r="255" g="0" b="0" />
  <color r="255" g="6" b="0" />
  <color r="255" g="12" b="0" />
  <color r="255" g="18" b="0" />
  <color r="255" g="24" b="0" />
  <color r="255" g="30" b="0" />
  <color r="255" g="36" b="0" />
  <color r="255" g="42" b="0" />
  <color r="255" g="48" b="0" />
  <color r="255" g="54" b="0" />
  <color r="255" g="60" b="0" />
  <color r="255" g="66" b="0" />
  <color r="255" g="72" b="0" />
  <color r="255" g="78" b="0" />
  <color r="255" g="84" b="0" />
  <color r="255" g="90" b="0" />
  <color r="255" g="96" b="0" />
  <color r="255" g="102" b="0" />
  <color r="255" g="108" b="0" />
  <color r="255" g="114" b="0" />
  <color r="255" g="120" b="0" />
  <color r="255" g="126" b="0" />
  <color r="255" g="132" b="0" />
  <color r="255" g="138" b="0" />
  <color r="255" g="144" b="0" />
  <color r="255" g="150" b="0" />
  <color r="255" g="156" b="0" />
  <color r="255" g="162" b="0" />
  <color r="255" g="168" b="0" />
  <color r="255" g="174" b="0" />
  <color r="255" g="180" b="0" />
  <color r="255" g="186" b="0" />
  <color r="255" g="192" b="0" />
  <color r="255" g="198" b="0" />
  <color r="255" g="204" b="0" />
  <color r="255" g="210" b="0" />
  <color r="255" g="216" b="0" />
  <color r="255" g="222" b="0" />
  <color r="255" g="228" b="0" />
  <color r="255" g="234" b="0" />
  <color r="255" g="240" b="0" />
  <color r="255" g="246" b="0" />
  <color r="255" g="252" b="0" />
  <color r="252" g="255" b="0" />
  <color r="246" g="255" b="0" />
  <color r="240" g="255" b="0" />
  <color r="234" g="255" b="0" />
  <color r="228" g="255" b="0" />
  <color r="222" g="255" b="0" />
  <color r="216" g="255" b="0" />
  <color r="210" g="255" b="0" />
  <color r="204" g="255" b="0" />
  <color r="198" g="255" b="0" />
  <color r="192" g="255" b="0" />
  <color r="186" g="255" b="0" />
  <color r="180" g="255" b="0" />
  <color r="174" g="255" b="0" />
  <color r="168" g="255" b="0" />
  <color r="162" g="255" b="0" />
  <color r="156" g="255" b="0" />
  <color r="150" g="255" b="0" />
  <color r="144" g="255" b="0" />
  <color r="138" g="255" b="0" />
  <color r="132" g="255" b="0" />
  <color r="126" g="255" b="0" />
  <color r="120" g="255" b="0" />
  <color r="114" g="255" b="0" />
  <color r="108" g="255" b="0" />
  <color r="102" g="255" b="0" />
  <color r="96" g="255" b="0" />
  <color r="90" g="255" b="0" />
  <color r="84" g="255" b="0" />
  <color r="78" g="255" b="0" />
  <color r="72" g="255" b="0" />
  <color r="66" g="255" b="0" />
  <color r="60" g="255" b="0" />
  <color r="54" g="255" b="0" />
  <color r="48" g="255" b="0" />
  <color r="42" g="255" b="0" />
  <color r="36" g="255" b="0" />
  <color r="30" g="255" b="0" />
  <color r="24" g="255" b="0" />
  <color r="18" g="255" b="0" />
  <color r="12" g="255" b="0" />
  <color r="6" g="255" b="0" />
  <color r="0" g="255" b="0" />
  <color r="0" g="255" b="6" />
  <color r="0" g="255" b="12" />
  <color r="0" g="255" b="18" />
  <color r="0" g="255" b="24" />
  <color r="0" g="255" b="30" />
  <color r="0" g="255" b="36" />
  <color r="0" g="255" b="42" />
  <color r="0" g="255" b="48" />
  <color r="0" g="255" b="54" />
  <color r="0" g="255" b="60" />
  <color r="0" g="255" b="66" />
  <color r="0" g="255" b="72" />
  <color r="0" g="255" b="78" />
  <color r="0" g="255" b="84" />
  <color r="0" g="255" b="90" />
  <color r="0" g="255" b="96" />
  <color r="0" g="255" b="102" />
  <color r="0" g="255" b="108" />
  <color r="0" g="255" b="114" />
  <color r="0" g="255" b="120" />
  <color r="0" g="255" b="126" />
  <color r="0" g="255" b="132" />
  <color r="0" g="255" b="138" />
  <color r="0" g="255" b="144" />
  <color r="0" g="255" b="150" />
  <color r="0" g="255" b="156" />
  <color r="0" g="255" b="162" />
  <color r="0" g="255" b="168" />
  <color r="0" g="255" b="174" />
  <color r="0" g="255" b="180" />
  <color r="0" g="255" b="186" />
  <color r="0" g="255" b="192" />
  <color r="0" g="255" b="198" />
  <color r="0" g="255" b="204" />
  <color r="0" g="255" b="210" />
  <color r="0" g="255" b="216" />
  <color r="0" g="255" b="222" />
  <color r="0" g="255" b="228" />
  <color r="0" g="255" b="234" />
  <color r="0" g="255" b="240" />
  <color r="0" g="255" b="246" />
  <color r="0" g="255" b="252" />
  <color r="0" g="252" b="255" />
  <color r="0" g="246" b="255" />
  <color r="0" g="240" b="255" />
  <color r="0" g="234" b="255" />
  <color r="0" g="228" b="255" />
  <color r="0" g="222" b="255" />
  <color r="0" g="216" b="255" />
  <color r="0" g="210" b="255" />
  <color r="0" g="204" b="255" />
  <color r="0" g="198" b="255" />
  <color r="0" g="192" b="255" />
  <color r="0" g="186" b="255" />
  <color r="0" g="180" b="255" />
  <color r="0" g="174" b="255" />
  <color r="0" g="168" b="255" />
  <color r="0" g="162" b="255" />
  <color r="0" g="156" b="255" />
  <color r="0" g="150" b="255" />
  <color r="0" g="144" b="255" />
  <color r="0" g="138" b="255" />
  <color r="0" g="132" b="255" />
  <color r="0" g="126" b="255" />
  <color r="0" g="120" b="255" />
  <color r="0" g="114" b="255" />
  <color r="0" g="108" b="255" />
  <color r="0" g="102" b="255" />
  <color r="0" g="96" b="255" />
  <color r="0" g="90" b="255" />
  <color r="0" g="84" b="255" />
  <color r="0" g="78" b="255" />
  <color r="0" g="72" b="255" />
  <color r="0" g="66" b="255" />
  <color r="0" g="60" b="255" />
  <color r="0" g="54" b="255" />
  <color r="0" g="48" b="255" />
  <color r="0" g="42" b="255" />
  <color r="0" g="36" b="255" />
  <color r="0" g="30" b="255" />
  <color r="0" g="24" b="255" />
  <color r="0" g="18" b="255" />
  <color r="0" g="12" b="255" />
  <color r="0" g="6" b="255" />
  <color r="0" g="0" b="255" />
  <color r="6" g="0" b="255" />
  <color r="12" g="0" b="255" />
  <color r="18" g="0" b="255" />
  <color r="24" g="0" b="255" />
  <color r="30" g="0" b="255" />
  <color r="36" g="0" b="255" />
  <color r="42" g="0" b="255" />
  <color r="48" g="0" b="255" />
  <color r="54" g="0" b="255" />
  <color r="60" g="0" b="255" />
  <color r="66" g="0" b="255" />
  <color r="72" g="0" b="255" />
  <color r="78" g="0" b="255" />
  <color r="84" g="0" b="255" />
  <color r="90" g="0" b="255" />
  <color r="96" g="0" b="255" />
  <color r="102" g="0" b="255" />
  <color r="108" g="0" b="255" />
  <color r="114" g="0" b="255" />
  <color r="120" g="0" b="255" />
  <color r="126" g="0" b="255" />
  <color r="132" g="0" b="255" />
  <color r="138" g="0" b="255" />
  <color r="144" g="0" b="255" />
  <color r="150" g="0" b="255" />
  <color r="156" g="0" b="255" />
  <color r="162" g="0" b="255" />
  <color r="168" g="0" b="255" />
  <color r="174" g="0" b="255" />
  <color r="180" g="0" b="255" />
  <color r="186" g="0" b="255" />
  <color r="192" g="0" b="255" />
  <color r="198" g="0" b="255" />
  <color r="204" g="0" b="255" />
  <color r="210" g="0" b="255" />
  <color r="216" g="0" b="255" />
  <color r="222" g="0" b="255" />
  <color r="228" g="0" b="255" />
  <color r="234" g="0" b="255" />
  <color r="240" g="0" b="255" />
  <color r="246" g="0" b="255" />
  <color r="252" g="0" b="255" />
  <color r="255" g="0" b="252" />
  <color r="255" g="0" b="246" />
  <color r="255" g="0" b="240" />
  <color r="255" g="0" b="234" />
  <color r="255" g="0" b="228" />
  <color r="255" g="0" b="222" />
  <color r="255" g="0" b="216" />
  <color r="255" g="0" b="210" />
  <color r="255" g="0" b="204" />
  <color r="255" g="0" b="198" />
  <color r="255" g="0" b="192" />
  <color r="255" g="0" b="186" />
  <color r="255" g="0" b="180" />
  <color r="255" g="0" b="174" />
  <color r="255" g="0" b="168" />
  <color r="255" g="0" b="162" />
  <color r="255" g="0" b="156" />
  <color r="255" g="0" b="150" />
  <color r="255" g="0" b="144" />
  <color r="255" g="0" b="138" />
  <color r="255" g="0" b="132" />
  <color r="255" g="0" b="126" />
  <color r="255" g="0" b="120" />
  <color r="255" g="0" b="114" />
  <color r="255" g="0" b="108" />
  <color r="255" g="0" b="102" />
  <color r="255" g="0" b="96" />
  <color r="255" g="0" b="90" />
  <color r="255" g="0" b="84" />
  <color r="255" g="0" b="78" />
  <color r="255" g="0" b="72" />
  <color r="255" g="0" b="66" />
  <color r="255" g="0" b="60" />
  <color r="255" g="0" b="54" />
  <color r="255" g="0" b="48" />
  <color r="255" g="0" b="42" />
  <color r="255" g="0" b="36" />
  <color r="255" g="0" b="30" />
  <color r="255" g="0" b="24" />
  <color r="255" g="0" b="18" />
  <color r="255" g="0" b="12" />
  <color r="255" g="0" b="6" />
  <color r="255" g="0" b="0" />
</palette>

=== phollemans/cwutils/resources/noaa/coastwatch/render/palettes/Coral-Reef-Degree-Heating-Week.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE palette SYSTEM "http://coastwatch.noaa.gov/xml/palette.dtd">
<palette name="Coral-Reef-Degree-Heating-Week" length="20">

<!-- Less than 0 -->
<!-- <color r="200" g="250" b="250" /> -->

<!-- 0 to 4 -->
<color r="70" g="50" b="120" />
<color r="100" g="80" b="150" />
<color r="130" g="110" b="180" />
<color r="160" g="140" b="210" />

<!-- 4 to 8 -->
<color r="255" g="255" b="0" />
<color r="255" g="220" b="0" />
<color r="255" g="185" b="0" />
<color r="255" g="150" b="0" />

<!-- 8 to 12 -->
<color r="255" g="0" b="0" />
<color r="210" g="0" b="0" />
<color r="160" g="0" b="0" />
<color r="110" g="0" b="0" />

<!-- 12 to 16 -->
<color r="230" g="125" b="70" />
<color r="180" g="90" b="40" />
<color r="125" g="60" b="30" />
<color r="85" g="45" b="20" />

<!-- 16 to 20 -->
<color r="240" g="0" b="240" />
<color r="200" g="0" b="200" />
<color r="160" g="0" b="160" />
<color r="120" g="0" b="120" />

<!-- Greater than 20 -->
<!-- <color r="50" g="0" b="50" /> -->

</palette>
