=== phollemans/cwutils/resources/noaa/coastwatch/render/palette.dtd
<!-- 

     FILE: palette.dtd
  PURPOSE: Defines the CoastWatch palette structure in XML.
   AUTHOR: Peter Hollemans
     DATE: 2004/05/16

  CoastWatch Software Library and Utilities
  Copyright 2004, USDOC/NOAA/NESDIS CoastWatch

-->

<!ELEMENT palette (color*)>
<!ATTLIST palette name CDATA #REQUIRED>
<!ATTLIST palette length CDATA #REQUIRED>
<!ELEMENT color EMPTY>
<!ATTLIST color r CDATA #REQUIRED>
<!ATTLIST color g CDATA #REQUIRED>
<!ATTLIST color b CDATA #REQUIRED>

=== phollemans/cwutils/resources/noaa/coastwatch/render/Steps.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE palette SYSTEM "http://coastwatch.noaa.gov/xml/palette.dtd">

<!-- This file was generated using data from the RSI IDL package v5.4 -->

<palette name="Steps" length="256">
  <color r="0" g="0" b="0" />
  <color r="0" g="42" b="0" />
  <color r="0" g="85" b="0" />
  <color r="0" g="127" b="0" />
  <color r="0" g="170" b="0" />
  <color r="0" g="212" b="0" />
  <color r="0" g="255" b="0" />
  <color r="0" g="246" b="0" />
  <color r="0" g="236" b="0" />
  <color r="0" g="226" b="0" />
  <color r="0" g="216" b="0" />
  <color r="0" g="206" b="0" />
  <color r="0" g="197" b="0" />
  <color r="0" g="187" b="0" />
  <color r="0" g="177" b="0" />
  <color r="0" g="167" b="0" />
  <color r="0" g="157" b="0" />
  <color r="0" g="148" b="0" />
  <color r="0" g="138" b="0" />
  <color r="0" g="128" b="0" />
  <color r="0" g="118" b="0" />
  <color r="0" g="108" b="0" />
  <color r="0" g="99" b="0" />
  <color r="0" g="89" b="0" />
  <color r="0" g="79" b="0" />
  <color r="0" g="69" b="0" />
  <color r="0" g="59" b="0" />
  <color r="0" g="50" b="0" />
  <color r="0" g="40" b="0" />
  <color r="0" g="30" b="0" />
  <color r="0" g="20" b="0" />
  <color r="0" g="10" b="0" />
  <color r="0" g="0" b="0" />
  <color r="0" g="0" b="8" />
  <color r="0" g="0" b="16" />
  <color r="0" g="0" b="24" />
  <color r="0" g="0" b="32" />
  <color r="0" g="0" b="41" />
  <color r="0" g="0" b="49" />
  <color r="0" g="0" b="57" />
  <color r="0" g="0" b="65" />
  <color r="0" g="0" b="74" />
  <color r="0" g="0" b="82" />
  <color r="0" g="0" b="90" />
  <color r="0" g="0" b="98" />
  <color r="0" g="0" b="106" />
  <color r="0" g="0" b="115" />
  <color r="0" g="0" b="123" />
  <color r="0" g="0" b="131" />
  <color r="0" g="0" b="139" />
  <color r="0" g="0" b="148" />
  <color r="0" g="0" b="156" />
  <color r="0" g="0" b="164" />
  <color r="0" g="0" b="172" />
  <color r="0" g="0" b="180" />
  <color r="0" g="0" b="189" />
  <color r="0" g="0" b="197" />
  <color r="0" g="0" b="205" />
  <color r="0" g="0" b="213" />
  <color r="0" g="0" b="222" />
  <color r="0" g="0" b="230" />
  <color r="0" g="0" b="238" />
  <color r="0" g="0" b="246" />
  <color r="0" g="0" b="255" />
  <color r="0" g="0" b="0" />
  <color r="7" g="0" b="5" />
  <color r="15" g="0" b="10" />
  <color r="23" g="0" b="15" />
  <color r="31" g="0" b="21" />
  <color r="39" g="0" b="26" />
  <color r="47" g="0" b="31" />
  <color r="55" g="0" b="37" />
  <color r="63" g="0" b="42" />
  <color r="70" g="0" b="47" />
  <color r="78" g="0" b="53" />
  <color r="86" g="0" b="58" />
  <color r="94" g="0" b="63" />
  <color r="102" g="0" b="69" />
  <color r="110" g="0" b="74" />
  <color r="118" g="0" b="79" />
  <color r="126" g="0" b="85" />
  <color r="134" g="0" b="89" />
  <color r="142" g="0" b="94" />
  <color r="151" g="0" b="98" />
  <color r="159" g="0" b="103" />
  <color r="168" g="0" b="108" />
  <color r="176" g="0" b="112" />
  <color r="184" g="0" b="117" />
  <color r="193" g="0" b="121" />
  <color r="201" g="0" b="126" />
  <color r="210" g="0" b="131" />
  <color r="218" g="0" b="135" />
  <color r="226" g="0" b="140" />
  <color r="235" g="0" b="144" />
  <color r="243" g="0" b="149" />
  <color r="252" g="0" b="154" />
  <color r="0" g="0" b="0" />
  <color r="1" g="0" b="0" />
  <color r="2" g="0" b="0" />
  <color r="3" g="0" b="0" />
  <color r="4" g="0" b="0" />
  <color r="5" g="0" b="0" />
  <color r="6" g="0" b="0" />
  <color r="7" g="0" b="0" />
  <color r="8" g="0" b="0" />
  <color r="9" g="0" b="0" />
  <color r="10" g="0" b="0" />
  <color r="11" g="0" b="0" />
  <color r="12" g="0" b="0" />
  <color r="14" g="0" b="0" />
  <color r="16" g="0" b="0" />
  <color r="18" g="0" b="0" />
  <color r="20" g="0" b="0" />
  <color r="23" g="0" b="0" />
  <color r="25" g="0" b="0" />
  <color r="27" g="0" b="0" />
  <color r="29" g="0" b="0" />
  <color r="32" g="0" b="0" />
  <color r="34" g="0" b="0" />
  <color r="36" g="0" b="0" />
  <color r="38" g="0" b="0" />
  <color r="41" g="0" b="0" />
  <color r="44" g="0" b="0" />
  <color r="47" g="0" b="0" />
  <color r="50" g="0" b="0" />
  <color r="53" g="0" b="0" />
  <color r="56" g="0" b="0" />
  <color r="59" g="0" b="0" />
  <color r="63" g="0" b="0" />
  <color r="66" g="0" b="0" />
  <color r="69" g="0" b="0" />
  <color r="72" g="0" b="0" />
  <color r="75" g="0" b="0" />
  <color r="78" g="0" b="0" />
  <color r="82" g="0" b="1" />
  <color r="85" g="0" b="1" />
  <color r="89" g="0" b="1" />
  <color r="93" g="0" b="1" />
  <color r="97" g="0" b="1" />
  <color r="101" g="0" b="1" />
  <color r="105" g="0" b="1" />
  <color r="108" g="0" b="1" />
  <color r="112" g="0" b="1" />
  <color r="116" g="0" b="1" />
  <color r="120" g="0" b="1" />
  <color r="124" g="0" b="1" />
  <color r="128" g="1" b="1" />
  <color r="131" g="1" b="1" />
  <color r="135" g="1" b="1" />
  <color r="139" g="1" b="1" />
  <color r="143" g="1" b="1" />
  <color r="147" g="1" b="1" />
  <color r="151" g="1" b="1" />
  <color r="155" g="1" b="1" />
  <color r="159" g="1" b="1" />
  <color r="163" g="1" b="1" />
  <color r="167" g="1" b="1" />
  <color r="171" g="1" b="1" />
  <color r="175" g="1" b="1" />
  <color r="178" g="1" b="1" />
  <color r="181" g="1" b="1" />
  <color r="185" g="1" b="1" />
  <color r="188" g="1" b="1" />
  <color r="192" g="1" b="1" />
  <color r="195" g="1" b="1" />
  <color r="198" g="1" b="1" />
  <color r="202" g="1" b="1" />
  <color r="205" g="1" b="1" />
  <color r="209" g="1" b="1" />
  <color r="212" g="1" b="1" />
  <color r="216" g="1" b="2" />
  <color r="218" g="1" b="2" />
  <color r="220" g="1" b="2" />
  <color r="223" g="1" b="2" />
  <color r="225" g="1" b="2" />
  <color r="227" g="1" b="2" />
  <color r="230" g="1" b="2" />
  <color r="232" g="1" b="2" />
  <color r="234" g="1" b="2" />
  <color r="237" g="1" b="2" />
  <color r="239" g="1" b="2" />
  <color r="241" g="1" b="2" />
  <color r="244" g="2" b="2" />
  <color r="244" g="2" b="2" />
  <color r="245" g="2" b="2" />
  <color r="246" g="2" b="2" />
  <color r="247" g="2" b="2" />
  <color r="247" g="2" b="2" />
  <color r="248" g="2" b="2" />
  <color r="249" g="2" b="2" />
  <color r="250" g="2" b="2" />
  <color r="250" g="2" b="2" />
  <color r="251" g="2" b="2" />
  <color r="252" g="2" b="2" />
  <color r="253" g="2" b="2" />
  <color r="254" g="1" b="2" />
  <color r="254" g="1" b="2" />
  <color r="254" g="3" b="2" />
  <color r="254" g="5" b="2" />
  <color r="254" g="8" b="2" />
  <color r="254" g="10" b="2" />
  <color r="254" g="12" b="2" />
  <color r="254" g="15" b="2" />
  <color r="254" g="17" b="2" />
  <color r="254" g="19" b="2" />
  <color r="254" g="22" b="2" />
  <color r="254" g="24" b="2" />
  <color r="254" g="26" b="2" />
  <color r="254" g="29" b="2" />
  <color r="254" g="31" b="2" />
  <color r="254" g="33" b="2" />
  <color r="254" g="36" b="2" />
  <color r="254" g="36" b="2" />
  <color r="254" g="38" b="3" />
  <color r="254" g="40" b="4" />
  <color r="254" g="42" b="5" />
  <color r="255" g="45" b="7" />
  <color r="255" g="48" b="9" />
  <color r="255" g="51" b="12" />
  <color r="255" g="54" b="14" />
  <color r="255" g="58" b="17" />
  <color r="255" g="61" b="20" />
  <color r="255" g="64" b="23" />
  <color r="255" g="67" b="27" />
  <color r="255" g="70" b="30" />
  <color r="255" g="73" b="34" />
  <color r="255" g="77" b="39" />
  <color r="255" g="82" b="44" />
  <color r="255" g="87" b="49" />
  <color r="255" g="92" b="55" />
  <color r="255" g="96" b="60" />
  <color r="255" g="100" b="65" />
  <color r="255" g="104" b="71" />
  <color r="255" g="108" b="76" />
  <color r="255" g="113" b="82" />
  <color r="255" g="119" b="89" />
  <color r="255" g="125" b="97" />
  <color r="255" g="131" b="104" />
  <color r="255" g="138" b="112" />
  <color r="255" g="144" b="120" />
  <color r="255" g="151" b="128" />
  <color r="255" g="157" b="136" />
  <color r="255" g="164" b="145" />
  <color r="255" g="171" b="153" />
  <color r="255" g="178" b="162" />
  <color r="255" g="185" b="171" />
  <color r="255" g="193" b="180" />
  <color r="255" g="200" b="189" />
  <color r="255" g="208" b="198" />
  <color r="255" g="215" b="207" />
  <color r="255" g="223" b="217" />
  <color r="255" g="229" b="224" />
  <color r="255" g="235" b="232" />
  <color r="255" g="242" b="239" />
  <color r="255" g="248" b="247" />
  <color r="255" g="255" b="255" />
</palette>

=== phollemans/cwutils/resources/noaa/coastwatch/render/Red-Temperature.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE palette SYSTEM "http://coastwatch.noaa.gov/xml/palette.dtd">

<!-- This file was generated using data from the RSI IDL package v5.4 -->

<palette name="Red-Temperature" length="256">
  <color r="0" g="0" b="0" />
  <color r="1" g="0" b="0" />
  <color r="2" g="0" b="0" />
  <color r="4" g="0" b="0" />
  <color r="5" g="0" b="0" />
  <color r="7" g="0" b="0" />
  <color r="8" g="0" b="0" />
  <color r="10" g="0" b="0" />
  <color r="11" g="0" b="0" />
  <color r="13" g="0" b="0" />
  <color r="14" g="0" b="0" />
  <color r="15" g="0" b="0" />
  <color r="17" g="0" b="0" />
  <color r="18" g="0" b="0" />
  <color r="20" g="0" b="0" />
  <color r="21" g="0" b="0" />
  <color r="23" g="0" b="0" />
  <color r="24" g="0" b="0" />
  <color r="26" g="0" b="0" />
  <color r="27" g="0" b="0" />
  <color r="28" g="0" b="0" />
  <color r="30" g="0" b="0" />
  <color r="31" g="0" b="0" />
  <color r="33" g="0" b="0" />
  <color r="34" g="0" b="0" />
  <color r="36" g="0" b="0" />
  <color r="37" g="0" b="0" />
  <color r="39" g="0" b="0" />
  <color r="40" g="0" b="0" />
  <color r="42" g="0" b="0" />
  <color r="43" g="0" b="0" />
  <color r="44" g="0" b="0" />
  <color r="46" g="0" b="0" />
  <color r="47" g="0" b="0" />
  <color r="49" g="0" b="0" />
  <color r="50" g="0" b="0" />
  <color r="52" g="0" b="0" />
  <color r="53" g="0" b="0" />
  <color r="55" g="0" b="0" />
  <color r="56" g="0" b="0" />
  <color r="57" g="0" b="0" />
  <color r="59" g="0" b="0" />
  <color r="60" g="0" b="0" />
  <color r="62" g="0" b="0" />
  <color r="63" g="0" b="0" />
  <color r="65" g="0" b="0" />
  <color r="66" g="0" b="0" />
  <color r="68" g="0" b="0" />
  <color r="69" g="0" b="0" />
  <color r="70" g="0" b="0" />
  <color r="72" g="0" b="0" />
  <color r="73" g="0" b="0" />
  <color r="75" g="0" b="0" />
  <color r="76" g="0" b="0" />
  <color r="78" g="0" b="0" />
  <color r="79" g="0" b="0" />
  <color r="81" g="0" b="0" />
  <color r="82" g="0" b="0" />
  <color r="84" g="0" b="0" />
  <color r="85" g="0" b="0" />
  <color r="86" g="0" b="0" />
  <color r="88" g="0" b="0" />
  <color r="89" g="0" b="0" />
  <color r="91" g="0" b="0" />
  <color r="92" g="0" b="0" />
  <color r="94" g="0" b="0" />
  <color r="95" g="0" b="0" />
  <color r="97" g="0" b="0" />
  <color r="98" g="0" b="0" />
  <color r="99" g="0" b="0" />
  <color r="101" g="0" b="0" />
  <color r="102" g="0" b="0" />
  <color r="104" g="0" b="0" />
  <color r="105" g="0" b="0" />
  <color r="107" g="0" b="0" />
  <color r="108" g="0" b="0" />
  <color r="110" g="0" b="0" />
  <color r="111" g="0" b="0" />
  <color r="113" g="0" b="0" />
  <color r="114" g="0" b="0" />
  <color r="115" g="0" b="0" />
  <color r="117" g="0" b="0" />
  <color r="118" g="0" b="0" />
  <color r="120" g="0" b="0" />
  <color r="121" g="0" b="0" />
  <color r="123" g="0" b="0" />
  <color r="124" g="0" b="0" />
  <color r="126" g="0" b="0" />
  <color r="127" g="0" b="0" />
  <color r="128" g="0" b="0" />
  <color r="130" g="0" b="0" />
  <color r="131" g="0" b="0" />
  <color r="133" g="0" b="0" />
  <color r="134" g="0" b="0" />
  <color r="136" g="0" b="0" />
  <color r="137" g="0" b="0" />
  <color r="139" g="0" b="0" />
  <color r="140" g="0" b="0" />
  <color r="141" g="0" b="0" />
  <color r="143" g="0" b="0" />
  <color r="144" g="0" b="0" />
  <color r="146" g="0" b="0" />
  <color r="147" g="0" b="0" />
  <color r="149" g="0" b="0" />
  <color r="150" g="0" b="0" />
  <color r="152" g="0" b="0" />
  <color r="153" g="0" b="0" />
  <color r="155" g="0" b="0" />
  <color r="156" g="0" b="0" />
  <color r="157" g="0" b="0" />
  <color r="159" g="0" b="0" />
  <color r="160" g="0" b="0" />
  <color r="162" g="0" b="0" />
  <color r="163" g="0" b="0" />
  <color r="165" g="0" b="0" />
  <color r="166" g="0" b="0" />
  <color r="168" g="0" b="0" />
  <color r="169" g="0" b="0" />
  <color r="170" g="0" b="0" />
  <color r="172" g="0" b="0" />
  <color r="173" g="0" b="0" />
  <color r="175" g="1" b="0" />
  <color r="176" g="3" b="0" />
  <color r="178" g="5" b="0" />
  <color r="179" g="7" b="0" />
  <color r="181" g="9" b="0" />
  <color r="182" g="11" b="0" />
  <color r="184" g="13" b="0" />
  <color r="185" g="15" b="0" />
  <color r="186" g="17" b="0" />
  <color r="188" g="18" b="0" />
  <color r="189" g="20" b="0" />
  <color r="191" g="22" b="0" />
  <color r="192" g="24" b="0" />
  <color r="194" g="26" b="0" />
  <color r="195" g="28" b="0" />
  <color r="197" g="30" b="0" />
  <color r="198" g="32" b="0" />
  <color r="199" g="34" b="0" />
  <color r="201" g="35" b="0" />
  <color r="202" g="37" b="0" />
  <color r="204" g="39" b="0" />
  <color r="205" g="41" b="0" />
  <color r="207" g="43" b="0" />
  <color r="208" g="45" b="0" />
  <color r="210" g="47" b="0" />
  <color r="211" g="49" b="0" />
  <color r="212" g="51" b="0" />
  <color r="214" g="52" b="0" />
  <color r="215" g="54" b="0" />
  <color r="217" g="56" b="0" />
  <color r="218" g="58" b="0" />
  <color r="220" g="60" b="0" />
  <color r="221" g="62" b="0" />
  <color r="223" g="64" b="0" />
  <color r="224" g="66" b="0" />
  <color r="226" g="68" b="0" />
  <color r="227" g="69" b="0" />
  <color r="228" g="71" b="0" />
  <color r="230" g="73" b="0" />
  <color r="231" g="75" b="0" />
  <color r="233" g="77" b="0" />
  <color r="234" g="79" b="0" />
  <color r="236" g="81" b="0" />
  <color r="237" g="83" b="0" />
  <color r="239" g="85" b="0" />
  <color r="240" g="86" b="0" />
  <color r="241" g="88" b="0" />
  <color r="243" g="90" b="0" />
  <color r="244" g="92" b="0" />
  <color r="246" g="94" b="0" />
  <color r="247" g="96" b="0" />
  <color r="249" g="98" b="0" />
  <color r="250" g="100" b="0" />
  <color r="252" g="102" b="0" />
  <color r="253" g="103" b="0" />
  <color r="255" g="105" b="0" />
  <color r="255" g="107" b="0" />
  <color r="255" g="109" b="0" />
  <color r="255" g="111" b="0" />
  <color r="255" g="113" b="0" />
  <color r="255" g="115" b="0" />
  <color r="255" g="117" b="0" />
  <color r="255" g="119" b="0" />
  <color r="255" g="120" b="0" />
  <color r="255" g="122" b="0" />
  <color r="255" g="124" b="0" />
  <color r="255" g="126" b="0" />
  <color r="255" g="128" b="0" />
  <color r="255" g="130" b="0" />
  <color r="255" g="132" b="0" />
  <color r="255" g="134" b="3" />
  <color r="255" g="136" b="7" />
  <color r="255" g="137" b="11" />
  <color r="255" g="139" b="15" />
  <color r="255" g="141" b="19" />
  <color r="255" g="143" b="23" />
  <color r="255" g="145" b="27" />
  <color r="255" g="147" b="31" />
  <color r="255" g="149" b="35" />
  <color r="255" g="151" b="39" />
  <color r="255" g="153" b="43" />
  <color r="255" g="154" b="47" />
  <color r="255" g="156" b="51" />
  <color r="255" g="158" b="54" />
  <color r="255" g="160" b="58" />
  <color r="255" g="162" b="62" />
  <color r="255" g="164" b="66" />
  <color r="255" g="166" b="70" />
  <color r="255" g="168" b="74" />
  <color r="255" g="170" b="78" />
  <color r="255" g="171" b="82" />
  <color r="255" g="173" b="86" />
  <color r="255" g="175" b="90" />
  <color r="255" g="177" b="94" />
  <color r="255" g="179" b="98" />
  <color r="255" g="181" b="102" />
  <color r="255" g="183" b="105" />
  <color r="255" g="185" b="109" />
  <color r="255" g="187" b="113" />
  <color r="255" g="188" b="117" />
  <color r="255" g="190" b="121" />
  <color r="255" g="192" b="125" />
  <color r="255" g="194" b="129" />
  <color r="255" g="196" b="133" />
  <color r="255" g="198" b="137" />
  <color r="255" g="200" b="141" />
  <color r="255" g="202" b="145" />
  <color r="255" g="204" b="149" />
  <color r="255" g="205" b="153" />
  <color r="255" g="207" b="156" />
  <color r="255" g="209" b="160" />
  <color r="255" g="211" b="164" />
  <color r="255" g="213" b="168" />
  <color r="255" g="215" b="172" />
  <color r="255" g="217" b="176" />
  <color r="255" g="219" b="180" />
  <color r="255" g="221" b="184" />
  <color r="255" g="222" b="188" />
  <color r="255" g="224" b="192" />
  <color r="255" g="226" b="196" />
  <color r="255" g="228" b="200" />
  <color r="255" g="230" b="204" />
  <color r="255" g="232" b="207" />
  <color r="255" g="234" b="211" />
  <color r="255" g="236" b="215" />
  <color r="255" g="238" b="219" />
  <color r="255" g="239" b="223" />
  <color r="255" g="241" b="227" />
  <color r="255" g="243" b="231" />
  <color r="255" g="245" b="235" />
  <color r="255" g="247" b="239" />
  <color r="255" g="249" b="243" />
  <color r="255" g="251" b="247" />
  <color r="255" g="253" b="251" />
  <color r="255" g="255" b="255" />
</palette>

=== phollemans/cwutils/resources/noaa/coastwatch/render/Chlora-1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE palette SYSTEM "http://coastwatch.noaa.gov/xml/palette.dtd">
<palette name="Chlora-1" length="101">
  <color r="132" g="0" b="124" />
  <color r="132" g="0" b="124" />
  <color r="124" g="0" b="131" />
  <color r="117" g="0" b="138" />
  <color r="110" g="0" b="145" />
  <color r="102" g="0" b="153" />
  <color r="95" g="0" b="160" />
  <color r="88" g="0" b="167" />
  <color r="80" g="0" b="174" />
  <color r="73" g="0" b="182" />
  <color r="66" g="0" b="189" />
  <color r="58" g="0" b="196" />
  <color r="51" g="0" b="204" />
  <color r="44" g="0" b="211" />
  <color r="36" g="0" b="218" />
  <color r="29" g="0" b="225" />
  <color r="22" g="0" b="233" />
  <color r="14" g="0" b="240" />
  <color r="7" g="0" b="247" />
  <color r="0" g="0" b="255" />
  <color r="0" g="14" b="255" />
  <color r="0" g="28" b="255" />
  <color r="0" g="42" b="255" />
  <color r="0" g="56" b="255" />
  <color r="0" g="70" b="255" />
  <color r="0" g="85" b="255" />
  <color r="0" g="99" b="255" />
  <color r="0" g="113" b="255" />
  <color r="0" g="127" b="255" />
  <color r="0" g="141" b="255" />
  <color r="0" g="155" b="255" />
  <color r="0" g="170" b="255" />
  <color r="0" g="184" b="255" />
  <color r="0" g="198" b="255" />
  <color r="0" g="212" b="255" />
  <color r="0" g="226" b="255" />
  <color r="0" g="240" b="255" />
  <color r="0" g="255" b="255" />
  <color r="0" g="255" b="231" />
  <color r="0" g="255" b="208" />
  <color r="0" g="255" b="185" />
  <color r="0" g="255" b="162" />
  <color r="0" g="255" b="139" />
  <color r="0" g="255" b="115" />
  <color r="0" g="255" b="92" />
  <color r="0" g="255" b="69" />
  <color r="0" g="255" b="46" />
  <color r="0" g="255" b="23" />
  <color r="0" g="255" b="0" />
  <color r="0" g="255" b="0" />
  <color r="21" g="255" b="0" />
  <color r="42" g="255" b="0" />
  <color r="63" g="255" b="0" />
  <color r="85" g="255" b="0" />
  <color r="106" g="255" b="0" />
  <color r="127" g="255" b="0" />
  <color r="148" g="255" b="0" />
  <color r="170" g="255" b="0" />
  <color r="191" g="255" b="0" />
  <color r="212" g="255" b="0" />
  <color r="233" g="255" b="0" />
  <color r="255" g="255" b="0" />
  <color r="255" g="244" b="0" />
  <color r="255" g="233" b="0" />
  <color r="255" g="223" b="0" />
  <color r="255" g="212" b="0" />
  <color r="255" g="201" b="0" />
  <color r="255" g="191" b="0" />
  <color r="255" g="180" b="0" />
  <color r="255" g="170" b="0" />
  <color r="255" g="159" b="0" />
  <color r="255" g="148" b="0" />
  <color r="255" g="138" b="0" />
  <color r="255" g="127" b="0" />
  <color r="255" g="116" b="0" />
  <color r="255" g="106" b="0" />
  <color r="255" g="95" b="0" />
  <color r="255" g="85" b="0" />
  <color r="255" g="74" b="0" />
  <color r="255" g="63" b="0" />
  <color r="255" g="53" b="0" />
  <color r="255" g="42" b="0" />
  <color r="255" g="31" b="0" />
  <color r="255" g="21" b="0" />
  <color r="255" g="10" b="0" />
  <color r="255" g="0" b="0" />
  <color r="247" g="0" b="0" />
  <color r="240" g="0" b="0" />
  <color r="232" g="0" b="0" />
  <color r="225" g="0" b="0" />
  <color r="217" g="0" b="0" />
  <color r="210" g="0" b="0" />
  <color r="202" g="0" b="0" />
  <color r="195" g="0" b="0" />
  <color r="187" g="0" b="0" />
  <color r="180" g="0" b="0" />
  <color r="180" g="100" b="100" />
  <color r="180" g="100" b="100" />
  <color r="180" g="100" b="100" />
  <color r="180" g="100" b="100" />
  <color r="180" g="100" b="100" />
</palette>

=== phollemans/cwutils/resources/noaa/coastwatch/render/palettes/Coral-Reef-Hotspot.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE palette SYSTEM "http://coastwatch.noaa.gov/xml/palette.dtd">
<palette name="Coral-Reef-Hotspot" length="50">

<!-- Less than 0 -->
<!-- <color r="200" g="250" b="250" /> -->

<!-- 0 to 1 -->

<color r="110" g="80" b="255" />
<color r="115" g="85" b="255" />
<color r="120" g="90" b="255" />
<color r="125" g="95" b="255" />
<color r="130" g="100" b="255" />

<color r="150" g="120" b="255" />
<color r="155" g="125" b="255" />
<color r="160" g="130" b="255" />
<color r="165" g="135" b="255" />
<color r="170" g="140" b="255" />

<!-- 1 to 2 -->

<color r="237" g="255" b="0" />
<color r="239" g="247" b="0" />
<color r="241" g="239" b="0" />
<color r="243" g="231" b="0" />
<color r="245" g="223" b="0" />

<color r="247" g="197" b="0" />
<color r="249" g="189" b="0" />
<color r="251" g="181" b="0" />
<color r="253" g="173" b="0" />
<color r="255" g="165" b="0" />

<!-- 2 to 3 -->

<color r="255" g="135" b="0" />
<color r="253" g="130" b="0" />
<color r="251" g="125" b="0" />
<color r="249" g="120" b="0" />
<color r="247" g="115" b="0" />

<color r="245" g="95" b="0" />
<color r="243" g="90" b="0" />
<color r="241" g="85" b="0" />
<color r="239" g="80" b="0" />
<color r="237" g="75" b="0" />

<!-- 3 to 4 -->

<color r="255" g="50" b="0" />
<color r="250" g="45" b="0" />
<color r="245" g="40" b="0" />
<color r="240" g="35" b="0" />
<color r="235" g="30" b="0" />

<color r="220" g="20" b="0" />
<color r="215" g="15" b="0" />
<color r="210" g="10" b="0" />
<color r="205" g="5" b="0" />
<color r="200" g="0" b="0" />

<!-- 4 to 5 -->

<color r="170" g="36" b="0" />
<color r="165" g="32" b="0" />
<color r="160" g="28" b="0" />
<color r="155" g="24" b="0" />
<color r="150" g="20" b="0" />

<color r="130" g="16" b="0" />
<color r="125" g="12" b="0" />
<color r="120" g="8" b="0" />
<color r="115" g="4" b="0" />
<color r="110" g="0" b="0" />

<!-- Greater than 5 -->
<!-- <color r="115" g="4" b="0" /> -->

</palette>
