=== phollemans/cwutils/resources/noaa/coastwatch/render/palette.dtd
<!-- 

     FILE: palette.dtd
  PURPOSE: Defines the CoastWatch palette structure in XML.
   AUTHOR: Peter Hollemans
     DATE: 2004/05/16

  CoastWatch Software Library and Utilities
  Copyright 2004, USDOC/NOAA/NESDIS CoastWatch

-->

<!ELEMENT palette (color*)>
<!ATTLIST palette name CDATA #REQUIRED>
<!ATTLIST palette length CDATA #REQUIRED>
<!ELEMENT color EMPTY>
<!ATTLIST color r CDATA #REQUIRED>
<!ATTLIST color g CDATA #REQUIRED>
<!ATTLIST color b CDATA #REQUIRED>

=== phollemans/cwutils/resources/noaa/coastwatch/render/Purple-Red-Stripes.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE palette SYSTEM "http://coastwatch.noaa.gov/xml/palette.dtd">

<!-- This file was generated using data from the RSI IDL package v5.4 -->

<palette name="Purple-Red-Stripes" length="256">
  <color r="0" g="0" b="0" />
  <color r="0" g="0" b="0" />
  <color r="127" g="127" b="127" />
  <color r="191" g="0" b="191" />
  <color r="188" g="0" b="192" />
  <color r="186" g="0" b="192" />
  <color r="184" g="0" b="193" />
  <color r="182" g="0" b="194" />
  <color r="179" g="0" b="195" />
  <color r="177" g="0" b="195" />
  <color r="140" g="0" b="157" />
  <color r="138" g="0" b="157" />
  <color r="170" g="0" b="198" />
  <color r="168" g="0" b="198" />
  <color r="165" g="0" b="199" />
  <color r="163" g="0" b="200" />
  <color r="161" g="0" b="201" />
  <color r="158" g="0" b="202" />
  <color r="156" g="0" b="202" />
  <color r="154" g="0" b="203" />
  <color r="121" g="0" b="163" />
  <color r="119" g="0" b="164" />
  <color r="147" g="0" b="205" />
  <color r="145" g="0" b="206" />
  <color r="142" g="0" b="207" />
  <color r="140" g="0" b="208" />
  <color r="138" g="0" b="208" />
  <color r="135" g="0" b="209" />
  <color r="133" g="0" b="210" />
  <color r="131" g="0" b="211" />
  <color r="103" g="0" b="169" />
  <color r="101" g="0" b="170" />
  <color r="124" g="0" b="213" />
  <color r="122" g="0" b="214" />
  <color r="119" g="0" b="215" />
  <color r="117" g="0" b="215" />
  <color r="115" g="0" b="216" />
  <color r="112" g="0" b="217" />
  <color r="110" g="0" b="218" />
  <color r="108" g="0" b="218" />
  <color r="84" g="0" b="175" />
  <color r="82" g="0" b="176" />
  <color r="101" g="0" b="221" />
  <color r="99" g="0" b="221" />
  <color r="96" g="0" b="222" />
  <color r="94" g="0" b="223" />
  <color r="92" g="0" b="224" />
  <color r="89" g="0" b="225" />
  <color r="87" g="0" b="225" />
  <color r="85" g="0" b="226" />
  <color r="66" g="0" b="181" />
  <color r="64" g="0" b="182" />
  <color r="78" g="0" b="228" />
  <color r="76" g="0" b="229" />
  <color r="73" g="0" b="230" />
  <color r="71" g="0" b="231" />
  <color r="69" g="0" b="231" />
  <color r="66" g="0" b="232" />
  <color r="64" g="0" b="233" />
  <color r="62" g="0" b="234" />
  <color r="47" g="0" b="188" />
  <color r="46" g="0" b="188" />
  <color r="55" g="0" b="236" />
  <color r="52" g="0" b="237" />
  <color r="50" g="0" b="238" />
  <color r="48" g="0" b="238" />
  <color r="46" g="0" b="239" />
  <color r="43" g="0" b="240" />
  <color r="41" g="0" b="241" />
  <color r="39" g="0" b="241" />
  <color r="29" g="0" b="194" />
  <color r="27" g="0" b="194" />
  <color r="32" g="0" b="244" />
  <color r="29" g="0" b="245" />
  <color r="27" g="0" b="245" />
  <color r="25" g="0" b="246" />
  <color r="23" g="0" b="247" />
  <color r="20" g="0" b="248" />
  <color r="18" g="0" b="248" />
  <color r="16" g="0" b="249" />
  <color r="11" g="0" b="200" />
  <color r="9" g="0" b="200" />
  <color r="9" g="0" b="251" />
  <color r="6" g="0" b="252" />
  <color r="4" g="0" b="253" />
  <color r="2" g="0" b="254" />
  <color r="0" g="0" b="255" />
  <color r="0" g="6" b="255" />
  <color r="0" g="12" b="255" />
  <color r="0" g="18" b="255" />
  <color r="0" g="19" b="204" />
  <color r="0" g="24" b="204" />
  <color r="0" g="36" b="255" />
  <color r="0" g="42" b="255" />
  <color r="0" g="48" b="255" />
  <color r="0" g="54" b="255" />
  <color r="0" g="60" b="255" />
  <color r="0" g="66" b="255" />
  <color r="0" g="72" b="255" />
  <color r="0" g="78" b="255" />
  <color r="0" g="68" b="204" />
  <color r="0" g="72" b="204" />
  <color r="0" g="97" b="255" />
  <color r="0" g="103" b="255" />
  <color r="0" g="109" b="255" />
  <color r="0" g="115" b="255" />
  <color r="0" g="121" b="255" />
  <color r="0" g="127" b="255" />
  <color r="0" g="133" b="255" />
  <color r="0" g="139" b="255" />
  <color r="0" g="116" b="204" />
  <color r="0" g="121" b="204" />
  <color r="0" g="157" b="255" />
  <color r="0" g="163" b="255" />
  <color r="0" g="170" b="255" />
  <color r="0" g="176" b="255" />
  <color r="0" g="182" b="255" />
  <color r="0" g="188" b="255" />
  <color r="0" g="194" b="255" />
  <color r="0" g="200" b="255" />
  <color r="0" g="165" b="204" />
  <color r="0" g="170" b="204" />
  <color r="0" g="218" b="255" />
  <color r="0" g="224" b="255" />
  <color r="0" g="230" b="255" />
  <color r="0" g="236" b="255" />
  <color r="0" g="242" b="255" />
  <color r="0" g="248" b="255" />
  <color r="0" g="255" b="255" />
  <color r="0" g="255" b="248" />
  <color r="0" g="204" b="194" />
  <color r="0" g="204" b="189" />
  <color r="0" g="255" b="230" />
  <color r="0" g="255" b="224" />
  <color r="0" g="255" b="218" />
  <color r="0" g="255" b="212" />
  <color r="0" g="255" b="206" />
  <color r="0" g="255" b="200" />
  <color r="0" g="255" b="194" />
  <color r="0" g="255" b="188" />
  <color r="0" g="204" b="145" />
  <color r="0" g="204" b="140" />
  <color r="0" g="255" b="169" />
  <color r="0" g="255" b="163" />
  <color r="0" g="255" b="157" />
  <color r="0" g="255" b="151" />
  <color r="0" g="255" b="145" />
  <color r="0" g="255" b="139" />
  <color r="0" g="255" b="133" />
  <color r="0" g="255" b="127" />
  <color r="0" g="204" b="97" />
  <color r="0" g="204" b="92" />
  <color r="0" g="255" b="109" />
  <color r="0" g="255" b="103" />
  <color r="0" g="255" b="97" />
  <color r="0" g="255" b="91" />
  <color r="0" g="255" b="84" />
  <color r="0" g="255" b="78" />
  <color r="0" g="255" b="72" />
  <color r="0" g="255" b="66" />
  <color r="0" g="204" b="48" />
  <color r="0" g="204" b="43" />
  <color r="0" g="255" b="48" />
  <color r="0" g="255" b="42" />
  <color r="0" g="255" b="36" />
  <color r="0" g="255" b="30" />
  <color r="0" g="255" b="24" />
  <color r="0" g="255" b="18" />
  <color r="0" g="255" b="12" />
  <color r="0" g="255" b="6" />
  <color r="0" g="204" b="0" />
  <color r="4" g="204" b="0" />
  <color r="12" g="255" b="0" />
  <color r="18" g="255" b="0" />
  <color r="24" g="255" b="0" />
  <color r="30" g="255" b="0" />
  <color r="36" g="255" b="0" />
  <color r="42" g="255" b="0" />
  <color r="48" g="255" b="0" />
  <color r="54" g="255" b="0" />
  <color r="48" g="204" b="0" />
  <color r="53" g="204" b="0" />
  <color r="72" g="255" b="0" />
  <color r="78" g="255" b="0" />
  <color r="85" g="255" b="0" />
  <color r="91" g="255" b="0" />
  <color r="97" g="255" b="0" />
  <color r="103" g="255" b="0" />
  <color r="109" g="255" b="0" />
  <color r="115" g="255" b="0" />
  <color r="97" g="204" b="0" />
  <color r="102" g="204" b="0" />
  <color r="133" g="255" b="0" />
  <color r="139" g="255" b="0" />
  <color r="145" g="255" b="0" />
  <color r="151" g="255" b="0" />
  <color r="157" g="255" b="0" />
  <color r="163" g="255" b="0" />
  <color r="170" g="255" b="0" />
  <color r="176" g="255" b="0" />
  <color r="145" g="204" b="0" />
  <color r="150" g="204" b="0" />
  <color r="194" g="255" b="0" />
  <color r="200" g="255" b="0" />
  <color r="206" g="255" b="0" />
  <color r="212" g="255" b="0" />
  <color r="218" g="255" b="0" />
  <color r="224" g="255" b="0" />
  <color r="230" g="255" b="0" />
  <color r="236" g="255" b="0" />
  <color r="194" g="204" b="0" />
  <color r="199" g="204" b="0" />
  <color r="255" g="255" b="0" />
  <color r="255" g="248" b="2" />
  <color r="255" g="242" b="5" />
  <color r="255" g="235" b="7" />
  <color r="255" g="229" b="10" />
  <color r="255" g="223" b="12" />
  <color r="255" g="216" b="15" />
  <color r="255" g="210" b="17" />
  <color r="204" g="163" b="16" />
  <color r="204" g="158" b="18" />
  <color r="255" g="191" b="25" />
  <color r="255" g="184" b="28" />
  <color r="255" g="178" b="30" />
  <color r="255" g="172" b="33" />
  <color r="255" g="165" b="35" />
  <color r="255" g="159" b="38" />
  <color r="255" g="153" b="40" />
  <color r="255" g="146" b="43" />
  <color r="204" g="112" b="36" />
  <color r="204" g="107" b="38" />
  <color r="255" g="127" b="51" />
  <color r="255" g="121" b="48" />
  <color r="255" g="115" b="46" />
  <color r="255" g="110" b="44" />
  <color r="255" g="104" b="41" />
  <color r="255" g="98" b="39" />
  <color r="255" g="92" b="37" />
  <color r="255" g="86" b="34" />
  <color r="204" g="64" b="25" />
  <color r="204" g="60" b="24" />
  <color r="255" g="69" b="27" />
  <color r="255" g="63" b="25" />
  <color r="255" g="57" b="23" />
  <color r="255" g="52" b="20" />
  <color r="255" g="46" b="18" />
  <color r="255" g="40" b="16" />
  <color r="255" g="34" b="13" />
  <color r="255" g="28" b="11" />
  <color r="204" g="18" b="7" />
  <color r="204" g="13" b="5" />
  <color r="255" g="11" b="4" />
  <color r="255" g="5" b="2" />
  <color r="255" g="0" b="0" />
  <color r="255" g="0" b="0" />
</palette>

=== phollemans/cwutils/resources/noaa/coastwatch/render/Eos-A.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE palette SYSTEM "http://coastwatch.noaa.gov/xml/palette.dtd">

<!-- This file was generated using data from the RSI IDL package v5.4 -->

<palette name="Eos-A" length="256">
  <color r="0" g="0" b="0" />
  <color r="0" g="0" b="0" />
  <color r="127" g="127" b="127" />
  <color r="123" g="0" b="193" />
  <color r="119" g="0" b="195" />
  <color r="114" g="0" b="197" />
  <color r="110" g="0" b="199" />
  <color r="106" g="0" b="201" />
  <color r="102" g="0" b="204" />
  <color r="97" g="0" b="206" />
  <color r="84" g="0" b="187" />
  <color r="80" g="0" b="189" />
  <color r="76" g="0" b="191" />
  <color r="80" g="0" b="214" />
  <color r="76" g="0" b="216" />
  <color r="72" g="0" b="218" />
  <color r="67" g="0" b="221" />
  <color r="63" g="0" b="223" />
  <color r="59" g="0" b="225" />
  <color r="55" g="0" b="227" />
  <color r="45" g="0" b="206" />
  <color r="42" g="0" b="208" />
  <color r="38" g="0" b="210" />
  <color r="38" g="0" b="235" />
  <color r="33" g="0" b="238" />
  <color r="29" g="0" b="240" />
  <color r="25" g="0" b="242" />
  <color r="21" g="0" b="244" />
  <color r="16" g="0" b="246" />
  <color r="12" g="0" b="248" />
  <color r="7" g="0" b="225" />
  <color r="3" g="0" b="227" />
  <color r="0" g="0" b="229" />
  <color r="0" g="17" b="255" />
  <color r="0" g="34" b="255" />
  <color r="0" g="51" b="255" />
  <color r="0" g="68" b="255" />
  <color r="0" g="85" b="255" />
  <color r="0" g="102" b="255" />
  <color r="0" g="119" b="255" />
  <color r="0" g="122" b="229" />
  <color r="0" g="137" b="229" />
  <color r="0" g="153" b="229" />
  <color r="0" g="187" b="255" />
  <color r="0" g="204" b="255" />
  <color r="0" g="221" b="255" />
  <color r="0" g="238" b="255" />
  <color r="0" g="255" b="255" />
  <color r="0" g="255" b="238" />
  <color r="0" g="255" b="221" />
  <color r="0" g="229" b="183" />
  <color r="0" g="229" b="168" />
  <color r="0" g="229" b="152" />
  <color r="0" g="255" b="153" />
  <color r="0" g="255" b="135" />
  <color r="0" g="255" b="118" />
  <color r="0" g="255" b="101" />
  <color r="0" g="255" b="84" />
  <color r="0" g="255" b="67" />
  <color r="0" g="255" b="50" />
  <color r="0" g="229" b="30" />
  <color r="0" g="229" b="15" />
  <color r="0" g="229" b="0" />
  <color r="8" g="255" b="0" />
  <color r="17" g="255" b="0" />
  <color r="25" g="255" b="0" />
  <color r="34" g="255" b="0" />
  <color r="42" g="255" b="0" />
  <color r="51" g="255" b="0" />
  <color r="59" g="255" b="0" />
  <color r="61" g="229" b="0" />
  <color r="68" g="229" b="0" />
  <color r="76" g="229" b="0" />
  <color r="93" g="255" b="0" />
  <color r="102" g="255" b="0" />
  <color r="110" g="255" b="0" />
  <color r="119" g="255" b="0" />
  <color r="127" g="255" b="0" />
  <color r="136" g="255" b="0" />
  <color r="144" g="255" b="0" />
  <color r="137" g="229" b="0" />
  <color r="145" g="229" b="0" />
  <color r="153" g="229" b="0" />
  <color r="178" g="255" b="0" />
  <color r="187" g="255" b="0" />
  <color r="195" g="255" b="0" />
  <color r="204" g="255" b="0" />
  <color r="212" g="255" b="0" />
  <color r="221" g="255" b="0" />
  <color r="229" g="255" b="0" />
  <color r="214" g="229" b="0" />
  <color r="221" g="229" b="0" />
  <color r="229" g="229" b="0" />
  <color r="255" g="250" b="0" />
  <color r="255" g="246" b="0" />
  <color r="255" g="242" b="0" />
  <color r="255" g="238" b="0" />
  <color r="255" g="233" b="0" />
  <color r="255" g="229" b="0" />
  <color r="255" g="225" b="0" />
  <color r="229" g="198" b="0" />
  <color r="229" g="195" b="0" />
  <color r="229" g="191" b="0" />
  <color r="255" g="208" b="0" />
  <color r="255" g="204" b="0" />
  <color r="255" g="199" b="0" />
  <color r="255" g="195" b="0" />
  <color r="255" g="191" b="0" />
  <color r="255" g="187" b="0" />
  <color r="255" g="182" b="0" />
  <color r="229" g="160" b="0" />
  <color r="229" g="156" b="0" />
  <color r="229" g="152" b="0" />
  <color r="255" g="165" b="0" />
  <color r="255" g="161" b="0" />
  <color r="255" g="157" b="0" />
  <color r="255" g="153" b="0" />
  <color r="255" g="148" b="0" />
  <color r="255" g="144" b="0" />
  <color r="255" g="140" b="0" />
  <color r="229" g="122" b="0" />
  <color r="229" g="118" b="0" />
  <color r="229" g="114" b="0" />
  <color r="255" g="125" b="0" />
  <color r="255" g="123" b="0" />
  <color r="255" g="121" b="0" />
  <color r="255" g="119" b="0" />
  <color r="255" g="116" b="0" />
  <color r="255" g="114" b="0" />
  <color r="255" g="112" b="0" />
  <color r="229" g="99" b="0" />
  <color r="229" g="97" b="0" />
  <color r="229" g="95" b="0" />
  <color r="255" g="104" b="0" />
  <color r="255" g="102" b="0" />
  <color r="255" g="99" b="0" />
  <color r="255" g="97" b="0" />
  <color r="255" g="95" b="0" />
  <color r="255" g="93" b="0" />
  <color r="255" g="91" b="0" />
  <color r="229" g="80" b="0" />
  <color r="229" g="78" b="0" />
  <color r="229" g="76" b="0" />
  <color r="255" g="82" b="0" />
  <color r="255" g="80" b="0" />
  <color r="255" g="78" b="0" />
  <color r="255" g="76" b="0" />
  <color r="255" g="74" b="0" />
  <color r="255" g="72" b="0" />
  <color r="255" g="70" b="0" />
  <color r="229" g="61" b="0" />
  <color r="229" g="59" b="0" />
  <color r="229" g="57" b="0" />
  <color r="255" g="61" b="0" />
  <color r="255" g="59" b="0" />
  <color r="255" g="57" b="0" />
  <color r="255" g="55" b="0" />
  <color r="255" g="53" b="0" />
  <color r="255" g="50" b="0" />
  <color r="255" g="48" b="0" />
  <color r="229" g="42" b="0" />
  <color r="229" g="40" b="0" />
  <color r="229" g="38" b="0" />
  <color r="255" g="40" b="0" />
  <color r="255" g="38" b="0" />
  <color r="255" g="36" b="0" />
  <color r="255" g="33" b="0" />
  <color r="255" g="31" b="0" />
  <color r="255" g="29" b="0" />
  <color r="255" g="27" b="0" />
  <color r="229" g="22" b="0" />
  <color r="229" g="21" b="0" />
  <color r="229" g="19" b="0" />
  <color r="255" g="19" b="0" />
  <color r="255" g="16" b="0" />
  <color r="255" g="14" b="0" />
  <color r="255" g="12" b="0" />
  <color r="255" g="13" b="0" />
  <color r="255" g="8" b="0" />
  <color r="255" g="6" b="0" />
  <color r="229" g="3" b="0" />
  <color r="229" g="1" b="0" />
  <color r="229" g="0" b="0" />
  <color r="253" g="0" b="0" />
  <color r="251" g="0" b="0" />
  <color r="249" g="0" b="0" />
  <color r="248" g="0" b="0" />
  <color r="246" g="0" b="0" />
  <color r="244" g="0" b="0" />
  <color r="242" g="0" b="0" />
  <color r="217" g="0" b="0" />
  <color r="215" g="0" b="0" />
  <color r="213" g="0" b="0" />
  <color r="236" g="0" b="0" />
  <color r="234" g="0" b="0" />
  <color r="232" g="0" b="0" />
  <color r="230" g="0" b="0" />
  <color r="229" g="0" b="0" />
  <color r="227" g="0" b="0" />
  <color r="225" g="0" b="0" />
  <color r="201" g="0" b="0" />
  <color r="200" g="0" b="0" />
  <color r="198" g="0" b="0" />
  <color r="218" g="0" b="0" />
  <color r="217" g="0" b="0" />
  <color r="215" g="0" b="0" />
  <color r="213" g="0" b="0" />
  <color r="211" g="0" b="0" />
  <color r="210" g="0" b="0" />
  <color r="208" g="0" b="0" />
  <color r="186" g="0" b="0" />
  <color r="184" g="0" b="0" />
  <color r="182" g="0" b="0" />
  <color r="201" g="0" b="0" />
  <color r="199" g="0" b="0" />
  <color r="198" g="0" b="0" />
  <color r="196" g="0" b="0" />
  <color r="194" g="0" b="0" />
  <color r="192" g="0" b="0" />
  <color r="191" g="0" b="0" />
  <color r="170" g="0" b="0" />
  <color r="169" g="0" b="0" />
  <color r="167" g="0" b="0" />
  <color r="184" g="0" b="0" />
  <color r="182" g="0" b="0" />
  <color r="180" g="0" b="0" />
  <color r="179" g="0" b="0" />
  <color r="177" g="0" b="0" />
  <color r="175" g="0" b="0" />
  <color r="174" g="0" b="0" />
  <color r="155" g="0" b="0" />
  <color r="153" g="0" b="0" />
  <color r="151" g="0" b="0" />
  <color r="167" g="0" b="0" />
  <color r="165" g="0" b="0" />
  <color r="163" g="0" b="0" />
  <color r="161" g="0" b="0" />
  <color r="160" g="0" b="0" />
  <color r="158" g="0" b="0" />
  <color r="156" g="0" b="0" />
  <color r="139" g="0" b="0" />
  <color r="138" g="0" b="0" />
  <color r="136" g="0" b="0" />
  <color r="149" g="0" b="0" />
  <color r="148" g="0" b="0" />
  <color r="146" g="0" b="0" />
  <color r="144" g="0" b="0" />
  <color r="143" g="0" b="0" />
  <color r="141" g="0" b="0" />
  <color r="139" g="0" b="0" />
  <color r="124" g="0" b="0" />
  <color r="122" g="0" b="0" />
  <color r="120" g="0" b="0" />
  <color r="132" g="0" b="0" />
  <color r="130" g="0" b="0" />
  <color r="130" g="0" b="0" />
</palette>

=== phollemans/cwutils/resources/noaa/coastwatch/render/Stern-Special.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE palette SYSTEM "http://coastwatch.noaa.gov/xml/palette.dtd">

<!-- This file was generated using data from the RSI IDL package v5.4 -->

<palette name="Stern-Special" length="256">
  <color r="0" g="0" b="0" />
  <color r="18" g="1" b="1" />
  <color r="36" g="2" b="3" />
  <color r="54" g="3" b="5" />
  <color r="72" g="4" b="7" />
  <color r="90" g="5" b="9" />
  <color r="108" g="6" b="11" />
  <color r="127" g="7" b="13" />
  <color r="145" g="8" b="15" />
  <color r="163" g="9" b="17" />
  <color r="181" g="10" b="19" />
  <color r="199" g="11" b="21" />
  <color r="217" g="12" b="23" />
  <color r="235" g="13" b="25" />
  <color r="254" g="14" b="27" />
  <color r="249" g="15" b="29" />
  <color r="244" g="16" b="31" />
  <color r="239" g="17" b="33" />
  <color r="234" g="18" b="35" />
  <color r="229" g="19" b="37" />
  <color r="223" g="20" b="39" />
  <color r="218" g="21" b="41" />
  <color r="213" g="22" b="43" />
  <color r="208" g="23" b="45" />
  <color r="203" g="24" b="47" />
  <color r="197" g="25" b="49" />
  <color r="192" g="26" b="51" />
  <color r="187" g="27" b="53" />
  <color r="182" g="28" b="55" />
  <color r="177" g="29" b="57" />
  <color r="172" g="30" b="59" />
  <color r="166" g="31" b="61" />
  <color r="161" g="32" b="63" />
  <color r="156" g="33" b="65" />
  <color r="151" g="34" b="67" />
  <color r="146" g="35" b="69" />
  <color r="140" g="36" b="71" />
  <color r="135" g="37" b="73" />
  <color r="130" g="38" b="75" />
  <color r="125" g="39" b="77" />
  <color r="120" g="40" b="79" />
  <color r="115" g="41" b="81" />
  <color r="109" g="42" b="83" />
  <color r="104" g="43" b="85" />
  <color r="99" g="44" b="87" />
  <color r="94" g="45" b="89" />
  <color r="89" g="46" b="91" />
  <color r="83" g="47" b="93" />
  <color r="78" g="48" b="95" />
  <color r="73" g="49" b="97" />
  <color r="68" g="50" b="99" />
  <color r="63" g="51" b="101" />
  <color r="58" g="52" b="103" />
  <color r="52" g="53" b="105" />
  <color r="47" g="54" b="107" />
  <color r="42" g="55" b="109" />
  <color r="37" g="56" b="111" />
  <color r="32" g="57" b="113" />
  <color r="26" g="58" b="115" />
  <color r="21" g="59" b="117" />
  <color r="16" g="60" b="119" />
  <color r="11" g="61" b="121" />
  <color r="6" g="62" b="123" />
  <color r="0" g="63" b="125" />
  <color r="64" g="64" b="127" />
  <color r="65" g="65" b="129" />
  <color r="66" g="66" b="131" />
  <color r="67" g="67" b="133" />
  <color r="68" g="68" b="135" />
  <color r="69" g="69" b="137" />
  <color r="70" g="70" b="139" />
  <color r="71" g="71" b="141" />
  <color r="72" g="72" b="143" />
  <color r="73" g="73" b="145" />
  <color r="74" g="74" b="147" />
  <color r="75" g="75" b="149" />
  <color r="76" g="76" b="151" />
  <color r="77" g="77" b="153" />
  <color r="78" g="78" b="155" />
  <color r="79" g="79" b="157" />
  <color r="80" g="80" b="159" />
  <color r="81" g="81" b="161" />
  <color r="82" g="82" b="163" />
  <color r="83" g="83" b="165" />
  <color r="84" g="84" b="167" />
  <color r="85" g="85" b="169" />
  <color r="86" g="86" b="171" />
  <color r="87" g="87" b="173" />
  <color r="88" g="88" b="175" />
  <color r="89" g="89" b="177" />
  <color r="90" g="90" b="179" />
  <color r="91" g="91" b="181" />
  <color r="92" g="92" b="183" />
  <color r="93" g="93" b="185" />
  <color r="94" g="94" b="187" />
  <color r="95" g="95" b="189" />
  <color r="96" g="96" b="191" />
  <color r="97" g="97" b="193" />
  <color r="98" g="98" b="195" />
  <color r="99" g="99" b="197" />
  <color r="100" g="100" b="199" />
  <color r="101" g="101" b="201" />
  <color r="102" g="102" b="203" />
  <color r="103" g="103" b="205" />
  <color r="104" g="104" b="207" />
  <color r="105" g="105" b="209" />
  <color r="106" g="106" b="211" />
  <color r="107" g="107" b="213" />
  <color r="108" g="108" b="215" />
  <color r="109" g="109" b="217" />
  <color r="110" g="110" b="219" />
  <color r="111" g="111" b="221" />
  <color r="112" g="112" b="223" />
  <color r="113" g="113" b="225" />
  <color r="114" g="114" b="227" />
  <color r="115" g="115" b="229" />
  <color r="116" g="116" b="231" />
  <color r="117" g="117" b="233" />
  <color r="118" g="118" b="235" />
  <color r="119" g="119" b="237" />
  <color r="120" g="120" b="239" />
  <color r="121" g="121" b="241" />
  <color r="122" g="122" b="243" />
  <color r="123" g="123" b="245" />
  <color r="124" g="124" b="247" />
  <color r="125" g="125" b="249" />
  <color r="126" g="126" b="251" />
  <color r="127" g="127" b="253" />
  <color r="128" g="128" b="255" />
  <color r="129" g="129" b="251" />
  <color r="130" g="130" b="247" />
  <color r="131" g="131" b="243" />
  <color r="132" g="132" b="238" />
  <color r="133" g="133" b="234" />
  <color r="134" g="134" b="230" />
  <color r="135" g="135" b="226" />
  <color r="136" g="136" b="221" />
  <color r="137" g="137" b="217" />
  <color r="138" g="138" b="213" />
  <color r="139" g="139" b="209" />
  <color r="140" g="140" b="204" />
  <color r="141" g="141" b="200" />
  <color r="142" g="142" b="196" />
  <color r="143" g="143" b="192" />
  <color r="144" g="144" b="187" />
  <color r="145" g="145" b="183" />
  <color r="146" g="146" b="179" />
  <color r="147" g="147" b="175" />
  <color r="148" g="148" b="170" />
  <color r="149" g="149" b="166" />
  <color r="150" g="150" b="162" />
  <color r="151" g="151" b="158" />
  <color r="152" g="152" b="153" />
  <color r="153" g="153" b="149" />
  <color r="154" g="154" b="145" />
  <color r="155" g="155" b="141" />
  <color r="156" g="156" b="136" />
  <color r="157" g="157" b="132" />
  <color r="158" g="158" b="128" />
  <color r="159" g="159" b="124" />
  <color r="160" g="160" b="119" />
  <color r="161" g="161" b="115" />
  <color r="162" g="162" b="111" />
  <color r="163" g="163" b="107" />
  <color r="164" g="164" b="102" />
  <color r="165" g="165" b="98" />
  <color r="166" g="166" b="94" />
  <color r="167" g="167" b="90" />
  <color r="168" g="168" b="85" />
  <color r="169" g="169" b="81" />
  <color r="170" g="170" b="77" />
  <color r="171" g="171" b="73" />
  <color r="172" g="172" b="68" />
  <color r="173" g="173" b="64" />
  <color r="174" g="174" b="60" />
  <color r="175" g="175" b="56" />
  <color r="176" g="176" b="51" />
  <color r="177" g="177" b="47" />
  <color r="178" g="178" b="43" />
  <color r="179" g="179" b="39" />
  <color r="180" g="180" b="34" />
  <color r="181" g="181" b="30" />
  <color r="182" g="182" b="26" />
  <color r="183" g="183" b="22" />
  <color r="184" g="184" b="17" />
  <color r="185" g="185" b="13" />
  <color r="186" g="186" b="9" />
  <color r="187" g="187" b="5" />
  <color r="188" g="188" b="0" />
  <color r="189" g="189" b="3" />
  <color r="190" g="190" b="7" />
  <color r="191" g="191" b="11" />
  <color r="192" g="192" b="15" />
  <color r="193" g="193" b="19" />
  <color r="194" g="194" b="22" />
  <color r="195" g="195" b="26" />
  <color r="196" g="196" b="30" />
  <color r="197" g="197" b="34" />
  <color r="198" g="198" b="38" />
  <color r="199" g="199" b="41" />
  <color r="200" g="200" b="45" />
  <color r="201" g="201" b="49" />
  <color r="202" g="202" b="53" />
  <color r="203" g="203" b="57" />
  <color r="204" g="204" b="60" />
  <color r="205" g="205" b="64" />
  <color r="206" g="206" b="68" />
  <color r="207" g="207" b="72" />
  <color r="208" g="208" b="76" />
  <color r="209" g="209" b="79" />
  <color r="210" g="210" b="83" />
  <color r="211" g="211" b="87" />
  <color r="212" g="212" b="91" />
  <color r="213" g="213" b="95" />
  <color r="214" g="214" b="98" />
  <color r="215" g="215" b="102" />
  <color r="216" g="216" b="106" />
  <color r="217" g="217" b="110" />
  <color r="218" g="218" b="114" />
  <color r="219" g="219" b="117" />
  <color r="220" g="220" b="121" />
  <color r="221" g="221" b="125" />
  <color r="222" g="222" b="129" />
  <color r="223" g="223" b="133" />
  <color r="224" g="224" b="137" />
  <color r="225" g="225" b="140" />
  <color r="226" g="226" b="144" />
  <color r="227" g="227" b="148" />
  <color r="228" g="228" b="152" />
  <color r="229" g="229" b="156" />
  <color r="230" g="230" b="159" />
  <color r="231" g="231" b="163" />
  <color r="232" g="232" b="167" />
  <color r="233" g="233" b="171" />
  <color r="234" g="234" b="175" />
  <color r="235" g="235" b="178" />
  <color r="236" g="236" b="182" />
  <color r="237" g="237" b="186" />
  <color r="238" g="238" b="190" />
  <color r="239" g="239" b="194" />
  <color r="240" g="240" b="197" />
  <color r="241" g="241" b="201" />
  <color r="242" g="242" b="205" />
  <color r="243" g="243" b="209" />
  <color r="244" g="244" b="213" />
  <color r="245" g="245" b="216" />
  <color r="246" g="246" b="220" />
  <color r="247" g="247" b="224" />
  <color r="248" g="248" b="228" />
  <color r="249" g="249" b="232" />
  <color r="250" g="250" b="235" />
  <color r="251" g="251" b="239" />
  <color r="252" g="252" b="243" />
  <color r="253" g="253" b="247" />
  <color r="254" g="254" b="251" />
  <color r="255" g="255" b="255" />
</palette>
